### PR TITLE
Update Kaldi backend to latest version

### PR DESCRIPTION
**Pull request by daanzu**
* **Direct Parsing**: parse recognitions directly on the FST, removing the (slow) `pyparsing` dependency.
    * Caster example: Loading is now **~50%** faster when cached, and the Kaldi backend accounts for only ~15% of loading time.
* **Python3**: both python 2 and 3 should be fully supported now.
    * **Unicode**: this should also fix unicode issues in various places in both python2/3.
* **Grammar/Rule Weights**: can specify weight, where grammars/rules with higher weight value are more likely to be recognized, compared to their peers, for an ambiguous recognition.
* **Generalized Alternative Dictation**: the cloud dictation feature has been generalized to make it easier to add other alternatives in the future.
* Various bug fixes & optimizations

### CODE REVIEW

**Comment by mrob95** [comment]
Looks good!

I've done a bit of testing on the mic dropping issue. It seems like under normal conditions, even if there is no speech, an audio block is generated by the iterator very regularly. As soon as the microphone drops the iterator just starts generating false all the time, even once the microphone is re-enabled.

How feasible would it be to put a check in the VAD collector so that as well as checking for activity it also checks for a period (say 0.5s) of complete inactivity, and then tries to close and reopen the audio stream?

**Comment by daanzu** [comment]
@mrob95 
> I've done a bit of testing on the mic dropping issue. It seems like under normal conditions, even if there is no speech, an audio block is generated by the iterator very regularly. As soon as the microphone drops the iterator just starts generating false all the time, even once the microphone is re-enabled.

A block should be yielded approximately every `block_duration_ms` (20). As far as I know, pyaudio doesn't notify when the interface has been dropped.

> How feasible would it be to put a check in the VAD collector so that as well as checking for activity it also checks for a period (say 0.5s) of complete inactivity, and then tries to close and reopen the audio stream?

Have you checked whether closing and reopening (calling the `stop`/`start` methods) successfully starts the stream again on the correct microphone? I am worried that it might choose the wrong one depending on the timing/order of the various events happening. Otherwise, this should be a good solution, which I could implement quickly.

**Comment by mrob95** [comment]
Have been testing this today. Closing the stream, reopening it with the same arguments and then starting it again works - dictation continues as usual. Helpful to have some printed feedback as well to indicate what's going on.

In my case, where I think the microphone is just dropping out for a very short time, it is successfully reconnecting to the same one. I guess if the microphone was actually disconnected it would get the next default microphone, if available, which is probably still a better result than just no recognitions.

**Comment by daanzu** [comment]
Ok, I will add an implementation of the audio fix for you to test out soon.

Also, oops, thanks for finding that other mistake, will fix.

**Comment by Danesprite** [comment]
I haven't gotten around to testing this yet, but these additions all look very good! I'm glad you've got the engine and KAG working with Python 3.

Adding grammar/rule weights is a great idea. It's probably possible to add something like this for the Sphinx engine too. Pocket Sphinx supports weighted alternatives, but they didn't seem to make much difference last time I tested them.

Regarding the audio stream issues, I haven't noticed issues like this with `pyaudio` on Linux using PulseAudio. I can switch the input device without issue.

I'll do some testing soon and see if I can any other issues :)

**Comment by daanzu** [comment]
@mrob95 Audio restarting should be ready for testing, among other improvements. Also updated the winpython dev distribution.

**Comment by mrob95** [comment]
The `restart` method needs to explicitly call `close` and `open` I think, otherwise it is just stopping and starting the same (dead) stream.

**Comment by daanzu** [comment]
@mrob95 Does this fix it? Do you need me to update the winpython distribution?

**Comment by mrob95** [comment]
Yes thanks, that's almost exactly what I've been using for the last couple of days and it's working fine, occasional disconnects but stable recovery.

No need to update the distribution if it's only me having this problem.

**Comment by Danesprite** [comment]
Hey @daanzu, sorry I haven't gotten back to you on this. I've done some testing now. I found a few issues with Python 3 which I haven't been able to reproduce after the first time they appeared. Python 2 still seems to work perfectly.

I actually dictated this post using Kaldi on linux without aenea! :D

I'm happy to merge this now if you think it's ready.

**Comment by daanzu** [comment]
Sure, this should be good to merge. I don't have anything significant to add without further testing.

Glad its working well! Please let me know of any py3 bugs that you can isolate.

**Comment by Danesprite** [comment]
All right then, I'll merge this now and keep an eye out for any Python 3 bugs :-)

I'd like to release version 0.18.0 tomorrow. Were there any other things you wanted to add?

**Pull request merged**
