### PR TITLE
Allow changing rules' and grammars' contexts after instantiation

### PR DESCRIPTION
**Pull request by Timoses**
This makes it possible to adjust contexts of grammars and rules after they have been instantiated.

Questions to be answered before merging:
* Are there any potential side effects? For example, could it occur that a context change happens during `process_recognition`?

### CODE REVIEW

**Comment by Danesprite** [comment]
Thanks for this. Sorry that I didn't get around to it myself.

Regarding your question on potential side effects: yes, it is possible for a context change to happen during `process_recognition()`. I don't think we should worry about such edge cases. Context changes in Dragonfly have always been detected in the grammar and rule `process_begin()` methods (i.e. speech start). I think this behaviour should just be documented in the docstrings for each `context` property. I'm happy to do that before merging.

**Comment by Danesprite** [comment]
I've think this might require complex handling of properties and class-level values. This is already done for `exported` in `MappingRule`, for example: https://github.com/dictation-toolbox/dragonfly/blob/587ffca034446fe85d77905515607534f8e8a664/dragonfly/grammar/rule_mapping.py#L121-L129

I'd like to avoid adding more code like this in the rule classes. Would a `set_context()` method and read-only `context` property be good enough instead?

**Comment by Timoses** [comment]
> I'd like to avoid adding more code like this in the rule classes. Would a set_context() method and read-only context property be good enough instead?

Absolutely! I will try to update the pull request tomorrow.

**Comment by Timoses** [comment]
How about this, @Danesprite ?

**Comment by Danesprite** [comment]
Thanks @Timoses, this is better. I see a few problems that I will fix tomorrow. I'll also improve the documentation a bit.

**Comment by Danesprite** [comment]
Okay, I think this is ready to merge. Does the documentation look all right to you?

**Comment by Timoses** [comment]
LGTM

**Pull request merged**
