### PR TITLE
Added typeable names so that all symbols can be referred to by their …

### PR DESCRIPTION
**Pull request by wolfmanstout**
…printable representation, except those reserved by the Key action spec syntax.

### CODE REVIEW

**Comment by wolfmanstout** [comment]
Note that we could actually include the four reserved characters as well -- it's just that Key wouldn't be able to use them because it would have parsed them as part of the spec syntax. In theory typeables.py is for more than just the Key action. On the other hand, this might cause confusion.

Unrelated note: _generate_typeables.py has not generally been kept up-to-date. I found it useful for generating this, though. We might consider removing it entirely or updating it and adding a note about it in typeables.py, instead of letting these quietly diverge.

**Comment by Danesprite** [comment]
Looks good. I think the reserved characters used by `Key` should just be added too if it doesn't break anything. A note about that could be added to the documentation for `Key` and the characters could be excluded in the last part of _generate_typeables.py.

I noticed a syntax error and a few other issues with _generate_typeables.py. I'd say lets keep it up-to-date and make a note in typeables.py. It makes generating the typeables list and `Key` documentation much easier.

We can make those adjustments in this PR too if you like.

**Comment by wolfmanstout** [comment]
Looks like I’m out of time this weekend, but I can follow up next weekend. I’m fine with doing the follow up improvements as part of this PR if you want; just need to know what they are other than the ones you listed. You are also welcome to make edits if you wish.

**Comment by Danesprite** [comment]
No problem. I noticed that some characters need to be escaped again when copy-pasted into typeables.py. I'll make some edits to fix those things and add the missing typeables added since the file was last changed.

I also noticed this would require changes to Aenea for it to work with that.

**Comment by Danesprite** [comment]
I didn't get around to making the edits I mentioned. I should be able to do that today.

**Comment by Danesprite** [comment]
Thanks for catching that. I have fixed it now. There's now little difference between the output from *_generate_typeables.py* and *typeables.py*.

**Pull request merged**
