### PR TITLE
Add Kaldi temporary mitigation for keyboard action processing bug (#182)

### PR DESCRIPTION
**Pull request by daanzu**
I am not sure how this will interact with `setup_log()`, as I don't have much experience with it.

### CODE REVIEW

**Comment by Danesprite** [comment]
Looks good to me. Hopefully we can one day figure out what's causing this problem! Should I release this in version 0.23.1 today?

Since this is the only work around we have, breaking `setup_log()` slightly doesn't seem like much of a big deal to me.

**Comment by daanzu** [comment]
About `setup_log()`: this fix doesn't turn on the logging if `setup_log()` is being used, but I am not exactly sure how to do so in that case. I guess I could just add another `stdout` handler for it?

Otherwise, releasing this fix sounds good. I was slacking by not getting it out for 0.23.0. 😉

**Comment by Danesprite** [comment]
I'm not sure either actually. Perhaps it should be logging to `sys.stderr` instead of `sys.stdout`? It looks like that's what `logging.basicConfig()` does.

That's alright. I didn't give any notice for version 0.23.0. I'll try to remember in the future :)

**Comment by daanzu** [comment]
It is all a bit mysterious, especially because I can't reproduce it at the moment. But when I could, I tried not enabling logging and instead adding a print statement at the same location. That didn't work; only the logging seemed to fix it.

**Comment by Danesprite** [comment]
Yes, it is quite mysterious. I'm happy to merge and release this now. Hopefully it fixes the problem for people!

I'll make some changes to `setup_log()` separately. It should probably be using `sys.stderr` anyway; printing diagnostic/error messages does seem to be the purpose of stderr after all.

**Comment by Danesprite** [comment]
Version 0.23.1 is released now. Should I close #182 or leave it open?

**Comment by daanzu** [comment]
I figure leave #182 open as a reminder until we can figure out the root cause.

**Comment by Danesprite** [comment]
Sounds good to me :+1:

**Pull request merged**
