### PR TITLE
Make some improvements to Dragonfly's macOS support

### PR DESCRIPTION
**Pull request by dmakarov**
This PR fixes the problem of identifying correctly windows of child process that share the same name but have unique IDs (e.g. all child processes of Caster have the same name Python).

### CODE REVIEW

**Comment by Danesprite** [comment]
Thanks for this! I was never happy with how `DarwinWindow` handles multiple windows of the same process or a process of the same name, so thank you for putting the time into fixing it.

It will need a few adjustments before merging. For example, the following usages don't work properly any more:

```Python
from dragonfly import BringApp, Window

BringApp("Firefox").execute()
print(Window.get_foreground().executable)
print(Window.get_foreground().pid)
print(Window.get_all_windows())


```

I think I can take care of fixing these things.

**Comment by dmakarov** [comment]
Some of this I fixed with the force-pushed update. `BringApp` doesn't seem to work on my system.

**Comment by dmakarov** [comment]
`Window.get_foreground().pid` won't work very well, because there may be several process with the same `exe` attribute

**Comment by Danesprite** [comment]
Thanks for the updates. `BringApp` isn't working because it relies on the `executable` property.

It is possible to get the window's process PID by using `unix id of ap` instead of `id of ap`. We can then find the full executable path using the PID and `psutil`. I've been having some success using it as the window ID instead.

The application `id` attribute isn't actually unique BTW. According to [Apple's documentation on this](https://developer.apple.com/library/archive/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_classes.html#//apple_ref/doc/uid/TP40000983-CH1g-DontLinkElementID_533), `id` is basically a short-form of the package bundle identifier.

**Comment by dmakarov** [comment]
Pushed more updates. Getting pid from unix id property and executable from name property

**Comment by dmakarov** [comment]
I think application id and application process id are different things. Application process is unique for every process in the system.

**Comment by dmakarov** [comment]
By the way the full executable path is also available as `file` propery of the application process element
`file -- the file from which the process was launched process`
Do you want to use that as `executable` attribute of a Window object?

**Comment by dmakarov** [comment]
Tell me, if the most recent updates everything works as expected.  It does find Firefox (Chrome in my case) with `BringApp` but on my system focus doesn't switch to the app (maybe because it's running in a different virtual desktop, than where I run the python script).  Otherwise as far as I can tell everything works.

**Comment by dmakarov** [comment]
Some background: I made these changes while fixing Caster on macOS. Currently (with this PR) mouse grids (as well as any other feature involving forking child python script process) do not work at all, because grid child process is not identified correctly. With this fix Caster mouse grid feature finally works on macOS.

**Comment by dmakarov** [comment]
maybe `StartApp._execute` on darwin could be changed to start a process `open -a <App Name>`?
It seems to work both to start a new application and to switch focus to a running application. For example, `open-a Safari` starts Safari browser from shell prompt, and `open -a 'Google Chrome'` switches focus to a running Chrome browser in my experiments.

**Comment by dmakarov** [comment]
`BringApp(["open", "-a", "Safari"]).execute()`
actually works quite well.  Maybe it's easier to change Caster to start applications or to switch focus to with via `open -a` on macOS

**Comment by Danesprite** [comment]
> I think application id and application process id are different things. Application process ID is unique for every process in the system.

Yes, you're right about this. I forgot there was a difference.

Regarding `window.executable`, I think it makes sense to use the full executable path from the `file` attribute. This is what is done on the other platforms. Perhaps the application *name* could be its own property?

Using `open -a <app-name>` for `BringApp` and `StartApp` on macOS also makes sense. For `StartApp`, it should use `open -n -a <app-name>` for starting a new application instance. If the `open` command fails, then we can log an error and fallback on the current behaviour of the actions.

Following on from that, perhaps `DarwinWindow.set_foreground()` should use `open -a <app-name>` instead? The `open` command seems to work better for me than `activate window 1`. To avoid confusing behaviour where `set_foreground()` actually *starts* programs, the method could first check if the PID or window ID exists. I can handle implementing this if you like.

> With this fix Caster mouse grid feature finally works on macOS.

This is great news!

**Comment by dmakarov** [comment]
I agree with all your comments. Would it make sense to merge this PR and do the open related changes on top of it? I think except for changing get_window_module to use `file` property, this PR has the necessary changes for further work on switching to using `open -a`. If you’re willing to add the `open -a` stuff, please go ahead.

**Comment by Danesprite** [comment]
I don't mind just renaming and reusing this PR for general fixes and improvements of Dragonfly's macOS support. I'll add the `open -a` command improvements in here later today and see if I can find any other issues before merging :-)

**Comment by Danesprite** [comment]
Sorry for the delay!

I've fixed `set_foreground()`. My previous idea of using the `open -a` command in that method would not have worked for multiple processes of the same application. It seems that we can't access or manipulate `window` attribute for application processes.

This has also broken the `get_attribute()` method and the properties that rely on it. I'll see if I can fix those by just using the executable name. That at least means those methods will mostly work, even if they don't work for multiple processes.

On the `executable` and app name properties, I can't get the `file` attribute you mentioned to work. I don't mind just leaving the `executable` property as the app name because the macOS way of launching applications seems to be quite different™ behind the scenes.

I still need to make the preposed modifications to the `StartApp` action. Neither the `BringApp` or `FocusWindow` actions really need to be changed.

**Comment by dmakarov** [comment]
Thanks for the update. No worries about the delay.

**Comment by Danesprite** [comment]
Okay that should do it. Let me know if this is working for you.

I'll do a re-base before merging because my commits are a bit messy.

**Comment by dmakarov** [comment]
Hi Dane,  it looks good to me.  How about just merge it, and if something comes up, we can fix that later?

**Comment by Danesprite** [comment]
Sounds good to me. I'll merge this shortly. I should be releasing the changes in version 0.21.0 later today.

**Comment by Danesprite** [comment]
Okay, all done. Thanks again! :+1:

**Pull request merged**
