### PR TITLE
Add dragonfly.rpc sub-package using JSON-RPC

### PR DESCRIPTION
**Pull request by Danesprite**
Re #24.

This implementation of *dragonfly.rpc* uses [JSON-RPC](https://www.jsonrpc.org/specification) instead of gRPC. I've done this in a new branch because feat/rpc was getting a little messy.

- [X] Implement dragonfly.rpc sub-package.
- [X] Add unit tests.
- [X] Add documentation page.
- [X] Add example RPC client script in dragonfly/examples.
- [X] Add RPC requirements to setup.py and documentation/requirements.txt: json-rpc, Werkzeug, requests.
- [X] Fix multi-threading issues I mentioned [here](https://github.com/dictation-toolbox/dragonfly/issues/24#issuecomment-458456878).
- [ ] Fix server security issue where malicious web pages can POST RPCs without the user's knowledge.
      I understand this can be fixed by requiring a security token be used to call methods. Thanks to @lunixbochs for finding a similar problem with Aenea.
      Ideally this can be done with a decorator to keep the method implementations simple.
- [x] Update documentation to mention the above security issue and that the server should not be used over an open network without using TLS or an SSH tunnel.
- [x] Update client example in *dragonfly/examples* to work as an authenticated client with minimal modification.
- [x] Also update client example to only print the names of loaded grammars and rules.

RPC server methods can be dynamically added, replaced and removed using the server's `add_method` and `remove_method` methods. This may be useful if you need the server to accept additional methods or to augment a current method implementation, e.g. make `list_grammars` handle custom rule classes.

### CODE REVIEW

**Comment by Danesprite** [comment]
I've discovered that natlink and WSR require some operations to be done on the main thread. Natlink extension module functions will raise errors if are called from other threads. WSR seems to fail silently. I haven't tested with Pocket Sphinx, but I know that the underlying C API is written to be re-entrant, so I doubt it has these issues. This won't effect methods that only interact with dragonfly like `list_grammars`.

The best way around this is to schedule RPC methods to be safely executed via dragonfly timers. This works perfectly for natlink already. I'll need to adjust the WSR backend to use a different timer manager class.

RPC methods which have this limitation should probably contain "async" in the name (e.g. `mimic_async`) and return `None` as the result. There could be equivalent synchronous methods which raise errors for unsupported engines.

On an unrelated note, I think the `list_grammars` method could be changed to `query_grammars` and have some options for retrieving certain grammars and rules.

**Comment by Danesprite** [comment]
Actually, I think it is far simpler to just schedule *all* RPC methods using an engine timer. This avoids having to deal with multi-threading outside of the methods file altogether. It also means that engines can allow multi-threading via the timer manager class they use.

I've devised and tested a way of synchronously passing the results from executed methods in the timer function back to the RPC client, so no need for the async methods. I'll push that once I've cleaned it up a bit and added a few more methods.

**Comment by LexiconCode** [comment]
That would simplify things quite a bit. Although I'm trying to put this in the context. For instance with natlink would that mean that the updates would be tied to dictation events?

**Comment by Danesprite** [comment]
It certainly does make things simpler. I've finished making it work properly for natlink. There are two additional methods: `mimic()` and `get_engine_language()`.

You can mimic stuff remotely now. E.g. with curl:

```Shell
curl --data-binary '{"jsonrpc":"2.0","id": "0","method": "mimic","params": ["test"]}' -H 'content-type:text/plain;' http://127.0.0.1:50051/jsonrpc

```

> For instance with natlink would that mean that the updates would be tied to dictation events?

No, the server uses an engine timer to process requests every second. For natlink this works regardless of the mic status. The timer shouldn't cause dragon to hang if there are lots of requests queued.

This is pretty obvious in retrospect, but I made dragonfly deadlock by testing it with a grammar command. Any RPC method run from the main thread will cause a deadlock and you'll have to reboot dragon manually.

**Comment by Danesprite** [comment]
So this will also work with WSR now. The *dfly-loader-wsr.py* file has been modified to use a new WSR `recognize_forever` engine method, which is the old recognition loop plus calling engine timers when appropriate. I've also added a `speak` RPC method.

@LexiconCode BTW if you look in the [methods.py file](https://github.com/dictation-toolbox/dragonfly/blob/feat/rpc-json/dragonfly/rpc/methods.py), the RPC methods themselves don't include any complicated thread synchronisation code. That's all handled by the `@rpc_method` decorator. The tests are also relatively straight forward. So new methods aren't too difficult to implement or test! :-)

**Comment by LexiconCode** [comment]
Fantastic work! This coming Wednesday I will work out implementing something fun :)

**Comment by Danesprite** [comment]
Thanks! Sounds good :+1:

This won't work with the Pocket Sphinx engine yet. I've added it to my long list of things to fix with that backend.

**Comment by Danesprite** [comment]
I've updated the to-do list to include a few more things. There is a security flaw with the server that could be abused by malicious web pages to control the machine via `mimic()` or other RPC methods. Admittedly this is a small project whose users might not be targeted by hackers, but I won't be merging this until the issue is resolved.

The server needs to have some client authentication to prevent the problem. That won't prevent other problems if it is used on an open network. In that case either TLS or an SSH tunnel (easier) should be used to have a secure connection.

**Comment by Danesprite** [comment]
Finally merged! 🎉

I'll fix the timer issues separately. One thing I forgot to do before I started merging was to make the server's natlink timer be called more frequently. That will make it more responsive.

**Comment by Danesprite** [comment]
I've kind of fixed the multi-threading issues with `ThreadedTimerManager` mentioned above. They occur mostly during the timer and RPC tests. If the current engine uses `ThreadedTimerManager`, its callbacks will be disabled during those test classes.

**Pull request merged**
