### PR TITLE
Kaldi updates

### PR DESCRIPTION
**Pull request by daanzu**
Not thoroughly tested, but here they are.

### CODE REVIEW

**Comment by Danesprite** [comment]
Thanks! I'll do some testing and see if I can find any problems :)

**Comment by Danesprite** [comment]
I think you need to update the required KAG version to 1.0.2. I got a few confusing errors when testing the `retain_data` and `retain_dir` parameters that were resolved by updating. Other than that, those parameters and the new `recognize_wave_file()` method are all working properly for me.

I've noticed some problems with dragonfly `Lists`. From my testing using the modules in `dragonfly/examples`, I can't get Kaldi to recognise `"list item"` after I say `"update list"`. Those commands are from the sphinx engine example module, but should work with any engine.

I sometimes got the following fatal error after trying to updating the list:

```Python
[KALDI severity=-3] Assertion failed: (grammar_fst_filename == grammar_fsts_filename_map[old_grammar_fst])
[1]    15045 abort      python kaldi_module_loader_plus.py
```

The recognition observer and list doctests are also failing when I run the Kaldi test suite. The `test_engine_kaldi.py` file also fails, but not if it runs before the doc tests as it used to before #162. The error tracebacks I'm getting are very long, so I'm not including them here. Any ideas on how to fix these?

**Comment by Danesprite** [comment]
I guess another minor thing would be to add commented arguments for `retain_dir` and `retain_audio` in the kaldi module loader and demo scripts in `dragonfly/examples`.

**Comment by Danesprite** [comment]
Okay, I've fixed those two things now. The error I resolved by upgrading KAG to 1.0.2 occurred after recognising "start listening" rather than use of the `retain*` arguments, so I didn't actually encounter any problems with those :)

Let me know if you want to fix the lists in another PR, I'm not sure how difficult that will be to fix.

**Comment by daanzu** [comment]
Thanks for the fixes.

Were you still having problems with lists after upgrading to 1.0.2? That should have fixed some issues with lists.

**Comment by Danesprite** [comment]
No worries.

No, lists still don't work properly after upgrading. Do they work on your end?

**Comment by daanzu** [comment]
Hmm, under further testing, I found some issues with lists. I hope to investigate and fix in a day or two. Up to you whether to merge this first or not.

**Comment by Danesprite** [comment]
Okay then, no rush. I'll just merge this now. Lists aren't used much so it's not really a big deal if we just leave that until version 0.19.1. I think lists are also broken on `master` anyway.

**Pull request merged**
