### PR TITLE
Change engine recognition loop method names to 'do_recognition'

### PR DESCRIPTION
**Pull request by Danesprite**
This is being done to unify the engine interface a bit. Aliases of renamed methods have been left in for backwards compatibility.

@daanzu @comodoro @jcaw This is the PR I mentioned on Gitter earlier.

### CODE REVIEW

**Comment by daanzu** [comment]
Is `recognize_forever` the best name if we are considering adding functionality to break out or otherwise interrupt the loop? That is why I chose `do_recognition` in the Kaldi backend. Just bringing it up; I have no problem if you want to merge, though.

**Comment by Danesprite** [comment]
I was wondering about this too actually. I can change it to `do_recognition`. Do you think the other engines should also use `timeout` and `single` parameters?

Regarding the recognition callback parameters, I can add them in this PR using the [register functions](https://dragonfly2.readthedocs.io/en/latest/recobs.html#recognition-state-change-callbacks) added in v0.18.

**Comment by daanzu** [comment]
I'm not sure that the timeout and single parameters are the best. I only added them on a whim; I haven't actually used them. There's probably a better design, but I haven't considered it much.

**Comment by Danesprite** [comment]
All right then, no worries. I think it may be cleaner to define `do_recognition` as a base class method and have each engine implement `_do_recognition`, similar to how the `load_grammar` and `_load_grammar` engine methods work.

The signature of `do_recognition` would be the following:
```Python
do_recognition(self, begin_callback=None, recognition_callback=None,
               failure_callback=None, *args, **kwargs)

```

That method would register the recognition callback functions and pass `args` and `kwargs` when calling `_do_recognition`, allowing for engine-specific parameters.

**Comment by daanzu** [comment]
Sounds great: nice, clean, and clear. 👍

**Comment by Danesprite** [comment]
Okay, I've done that now. I've also changed the module loader scripts to all use `do_recognition()`.

One other thing I'd like to do is move/copy the REPL code for the `dragonfly test ...` command into a base engine method and have the text engine call it for `_do_recognition()`.

**Comment by Danesprite** [comment]
I just ended up using the REPL code directly in the text engine's `_do_recognition()` method. You wouldn't really need to use it for any other engine anyway.

The only thing left to do now is make `engine.disconnect()` break out of the recognition loop for the SAPI5, Kaldi and text engines. Natlink's `_do_recognition()` method opens a dialog box for exiting the loop instead and sphinx's recognition loop already exits on `disconnect()`.

**Comment by Danesprite** [comment]
All done now.

To be consistent, I have also changed the natlink engine. `disconnect()` effectively closes the `waitForSpeech()` dialog box for you if it is still active. This doesn't effect the normal way natlink is used via natspeak.exe.

**Pull request merged**
