### PR TITLE
Enhance engine dependency checks and log messages

### PR DESCRIPTION
**Pull request by LexiconCode**
The purpose of this pull request is to enhance error messages related to dependencies for speech recognition engines.  These checks will help inform users during call to get engine and the CLI.

The enhancements include:
Natlink
- Checking OS (only Windows is supported)
- Rewording message checking for natlink clarifying that it needs to be installed.
- Checking python environment to ensure its 32-bit
WSR
- Checking OS (only Windows is supported)
kaldi
- Checking python environment to ensure its 64-bit
All Backends
- Check if the requested engine name is a supported engine.

Example output
```
PS D:\Backup\Library\Documents\Caster> cmd /c python -m dragonfly load --engine foo _caster.py
ERROR:command:Requested engine 'foo' is not a valid engine name.
```

### CODE REVIEW

**Comment by Danesprite** [comment]
Thanks for this! As you mentioned to me privately, there are also a few redundant log messages that should be removed.

The 32-bit check is a good idea. Maybe it should be above the `import natlink` block though, as natlink will never be importable in 64-bit Python.

**Comment by LexiconCode** [comment]
> 
> 
> Thanks for this! As you mentioned to me privately, there are also a few redundant log messages that should be removed.
> 
> The 32-bit check is a good idea. Maybe it should be above the `import natlink` block though, as natlink will never be importable in 64-bit Python.

You're welcome and thanks for the feedback! 

An example of the duplicate logging.
```
# <-- Initial exception from my code
EngineError: 'Windows' is not currently supported by Natlink. 

# <-- from dragonfly\engines\__init__.py

# log.exception(message)
Exception while initializing natlink engine: 'Windows' is not currently supported by Natlink. # 

# print(message)
ERROR:command:Exception while initializing natlink engine: 'Windows' is not currently supported by Natlink. 
```
So the question is how do we want to handle the duplicate logging. What was the intent behind having and `log.exception(message)` and `print(message)` Perhaps `print(message)` only displays in the natlink status/messages window?

**Comment by LexiconCode** [comment]
It seems that this bit of code could be removed from the end of all loaders. Which leaves `log.exception(message)` to print the log and EngineError the its message.
```
            traceback.print_exc()
            print(message)
            if name:
                raise EngineError(message)
```
With the suggested change the traceback.
```
Traceback (most recent call last):
  File "d:\backup\library\documents\dragonfly\dragonfly\engines\__init__.py", line 71, in get_engine
    _default_engine = get_specific_engine(**kwargs)
  File "d:\backup\library\documents\dragonfly\dragonfly\engines\backend_natlink\__init__.py", line 89, in get_engine
    _engine = NatlinkEngine(**kwargs)
  File "d:\backup\library\documents\dragonfly\dragonfly\engines\backend_natlink\engine.py", line 79, in __init__
    raise EngineError("'{}' is not currently supported by Natlink.".format(self.platform))
EngineError: 'Windows' is not currently supported by Natlink.
ERROR:command:Requested engine 'natlink' not available.
```

**Comment by Danesprite** [comment]
Yep, I think the issue is that `get_engine()` both raises *and* logs errors. So the idea is to remove the following two lines from all engine init blocks:

```Python
            traceback.print_exc()
            print(message)

```

I think these messages should still be printed when the `name` argument is unspecified. That way, users will know if the wrong engine has been initialized and for what reason (e.g. `natlink` instead of `sapi5inproc`). The messages will also be printed if no engines are available. 

Following on from that, I think that unless they're explicitly specified, Windows-only engines should not be considered on other platforms. I'll push changes for that shortly.

**Comment by LexiconCode** [comment]
Since kaldi requires a 64-bit Python environment should we include that check as well?

**Comment by Danesprite** [comment]
Yep. That sounds like a good idea to me.

**Comment by LexiconCode** [comment]
All right this should be good to go! A bit messy commit history on my part but it works out for the best.

**Comment by Danesprite** [comment]
I don't think this is quite ready yet. I'd like to clean up each `is_engine_available()` function a bit before merging.

**Comment by Danesprite** [comment]
As for the commit messages, maybe I could clean it up with a rebase prior to merging?

**Comment by LexiconCode** [comment]
Feel free to do what you gotta do!

**Comment by Danesprite** [comment]
Okay, I've cleaned them up now. Each log function can take formatting arguments BTW:

```Python
_log.exception("Exception during import of natlink package: %s", e)
# vs
_log.exception("Exception during import of natlink package: %s" % (e,))
```

I've also added the Windows OS checks into the Natlink and SAPI5 `is_engine_available()` functions in case `get_engine("natlink")` is called on other platform. I'm wondering whether the log messages should use `log.warning()` rather than `log.info()`. That way they would show up by default.

**Comment by LexiconCode** [comment]
I would have them show up by default via `log.warning()`.

**Comment by Danesprite** [comment]
I agree. I'll change them now.

I've noticed the functions for Kaldi and Sphinx log no error messages if the `ENGINE_AVAILABLE` variable is `False`. The original intent for that variable was to allow importing the engines for the documentation build, but I think there is a cleaner way of doing that, which I should be able to add before merging.

Just FYI @daanzu, I'll be changing the imports in `backend_kaldi/engine.py`.

**Comment by Danesprite** [comment]
All done. The build is failing because the repository couldn't be cloned from GitHub, but only in the Python 3.5 environment :woman_shrugging:

I'll rebase this now then merge.

**Pull request merged**
