### PR TITLE
Add magic repr methods for debugging

### PR DESCRIPTION
**Pull request by mrob95**
Is there a good reason not to do this?

### CODE REVIEW

**Comment by daanzu** [comment]
Good idea! However, I think idiomatic python is actually to define a `__repr__` and no `__str__` in this case, because then python's default str implementation just calls repr. This is my standard approach.

**Comment by Danesprite** [comment]
Thanks for this @mrob95! The lack of `__repr__` methods in some classes has also been bothering me lately.

@daanzu I didn't know Python did that with `__repr__`. I suppose we could just rename `__str__` to `__repr__` in some places. Some classes rely on `__unicode__` instead though.

**Comment by daanzu** [comment]
I definitely think renaming `__str__` to `__repr__` is the right thing to do. I don't have much experience messing around with `__unicode__`, though I think the default implementation just calls str and then decodes it in the system text encoding.

**Comment by Danesprite** [comment]
Yep, seems like it. I'll have a look into that.

**Comment by mrob95** [comment]
If str calls repr then there is no reason to have both. Shall I switch it for the classes I have edited here? I only did the ones anyone is likely to want to print out for debugging.

**Comment by Danesprite** [comment]
Sure, go ahead and define `__repr__` on the base classes :)

**Comment by Danesprite** [comment]
Thanks again Mike! I'll merge this now.

**Pull request merged**
