### PR TITLE
Update Kaldi backend

### PR DESCRIPTION
**Pull request by daanzu**
[KaldiAG v2.0.0](https://github.com/daanzu/kaldi-active-grammar/releases/tag/v2.0.0)

* Native FST support, via direct wrapping of OpenFST, rather than Python text-format implementation
    * Eliminates grammar (G) FST compilation step
* Internalized many graph construction steps, via direct use of native Kaldi/OpenFST functions, rather than invoking separate CLI processes
    * Eliminates need for many temporary files (FSTs, `.conf`s, etc) and pipes
* OpenBLAS is now the default linear algebra library (rather than Intel MKL) on Linux/MacOS
    * Because it is open source and provides good performance on all hardware (including AMD)
    * Windows is more difficult for this, and will be implemented soon in a later release
* Default `tmp_dir` is now set to `[model_dir]/cache.tmp`
* `tmp_dir` is now optional, and only needed if caching compiled FSTs (or for certain framework/option combinations)
* File cache is now stored at `[model_dir]/file_cache.json`
* Optimized adding many new words to the lexicon, in many different grammars, all in one loading session: only rebuild `L_disambig.fst` once at the end.
* Python 2.7 support ended: it may still work, but will not be a focus.
* Google cloud speech-to-text removed, as an unneeded dependency. Alternative dictation is still supported as an option, via a callback to an external provider.

### CODE REVIEW

**Comment by daanzu** [comment]
Oops, forgot to push documentation. Should be good now.

**Comment by Danesprite** [comment]
Thanks! Unfortunately, I'm getting a few errors on Linux using `kaldi_model_daanzu_20200905_1ep-smalllm` as the model. I think this might have already been happening before the update.

I get the following error when running the test suite:

```
running test
Test suite running for engine 'kaldi'
engine (INFO): Loading Kaldi-Active-Grammar v2.0.2 in process 22622.
engine (INFO): Kaldi options: {'model_dir': None, 'tmp_dir': None, 'audio_input_device': False, 'audio_self_threaded': True, 'audio_auto_reconnect': True, 'audio_reconnect_callback': None, 'retain_dir': None, 'retain_audio': False, 'retain_metadata': False, 'retain_approval_func': None, 'vad_aggressiveness': 3, 'vad_padding_start_ms': 150, 'vad_padding_end_ms': 200, 'vad_complex_padding_end_ms': 600, 'auto_add_to_user_lexicon': True, 'lazy_compilation': True, 'invalidate_cache': False, 'expected_error_rate_threshold': None, 'alternative_dictation': None, 'compiler_init_config': {}, 'decoder_init_config': {}}

[I've removed irrelevant test suite output here. Everything up to this point passes. - Ed.]

documentation/test_grammar_list_doctest.txt F
documentation/test_recobs_doctest.txt [KALDI severity=-1] Context FST created but there are no phone symbols: probably input FST was empty.
[KALDI severity=-3] Assertion failed: (hclg_fst.Start() != fst::kNoStateId)
Fatal Python error: Aborted

Current thread 0x00007f6b1ba89700 (most recent call first):
  File "/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/wrapper.py", line 534 in compile_graph
  File "/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/compiler.py", line 418 in _compile_agf_graph
  File "/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/compiler.py", line 130 in finish_compile
  File "/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/compiler.py", line 587 in <lambda>
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57 in run
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 80 in _worker
  File "/usr/lib/python3.7/threading.py", line 865 in run
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 885 in _bootstrap

Thread 0x00007f6b48aaf740 (most recent call first):
  File "/usr/lib/python3.7/threading.py", line 296 in wait
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 427 in result
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 586 in result_iterator
  File "/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/compiler.py", line 593 in process_compile_and_load_queues
  File "/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/compiler.py", line 620 in prepare_for_recognition
  File "/home/dane/repos/dragonfly/dragonfly/engines/backend_kaldi/engine.py", line 333 in prepare_for_recognition
  File "/home/dane/repos/dragonfly/dragonfly/engines/backend_kaldi/engine.py", line 550 in _compute_kaldi_rules_activity
  File "/home/dane/repos/dragonfly/dragonfly/engines/backend_kaldi/engine.py", line 300 in mimic
  File "/home/dane/repos/dragonfly/dragonfly/test/element_tester.py", line 74 in recognize
  File "<doctest test_recobs_doctest.txt[6]>", line 1 in <module>

  [I've removed about 50 irrelevant test suite traceback lines here. - Ed.]

  File "/home/dane/repos/dragonfly/dragonfly/test/suites.py", line 173 in run_pytest_suite
  File "setup.py", line 67 in run
  File "/usr/lib/python3.7/distutils/dist.py", line 985 in run_command
  File "/usr/lib/python3.7/distutils/dist.py", line 966 in run_commands
  File "/usr/lib/python3.7/distutils/core.py", line 148 in setup
  File "/home/dane/.local/lib/python3.7/site-packages/setuptools/__init__.py", line 153 in setup
  File "setup.py", line 164 in <module>
[1]    22622 abort      python3 setup.py test --test-suite=kaldi -o -s

```

I think this is the same error, caused by use of a Dragonfly `List` in one of my command modules:
```
  File "/home/dane/repos/dragonfly/dragonfly/grammar/grammar_base.py", line 453, in load
    lst._update()
  File "/home/dane/repos/dragonfly/dragonfly/grammar/list.py", line 115, in _update
    self._grammar.update_list(self)
  File "/home/dane/repos/dragonfly/dragonfly/grammar/grammar_base.py", line 424, in update_list
    self._engine.update_list(lst, self)
  File "/home/dane/repos/dragonfly/dragonfly/engines/backend_kaldi/engine.py", line 278, in update_list
    self._compiler.update_list(lst, grammar)
  File "/home/dane/repos/dragonfly/dragonfly/engines/backend_kaldi/compiler.py", line 206, in update_list
    with kaldi_rule.reload():
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dane/.local/lib/python3.7/site-packages/kaldi_active_grammar/compiler.py", line 185, in reload
    self.fst.clear()
AttributeError: 'NativeWFST' object has no attribute 'clear'
[KALDI severity=-1] Context FST created but there are no phone symbols: probably input FST was empty.
[KALDI severity=-3] Assertion failed: (hclg_fst.Start() != fst::kNoStateId)

```

Are you able to replicate this problem?

**Comment by daanzu** [comment]
@Danesprite Oops, thanks for catching that! I will take a look. I did release a minor update of KaldiAG to v2.0.2, but it certainly doesn't fix some of those errors.

**Comment by LexiconCode** [comment]
Should the continuous integration catch this in the PR if these are part of unit test?

**Comment by Danesprite** [comment]
@daanzu Okay then :+1:. Let me know if you need more info from me.

@LexiconCode Good question. The continuous integration (Travis CI) runs Dragonfly's test suite using the "text" engine backend. It is impractical to run the test suite using a real SR engine back-end like Kaldi. Not catching errors like this in an automated fashion is okay, it only means the test suite must be run manually to test the real engine back-ends properly. This should be done on each supported platform.

**Comment by daanzu** [comment]
@Danesprite @LexiconCode Actually, I've been working on setting up Continuous Integration testing running Kaldi through Dragonfly using generated wave files. Obviously none too soon 😉, but I don't have it fully running yet.

**Comment by Danesprite** [comment]
Oh, okay then. That's a good idea, though I would still prefer using mimic for the tests. One reason is that mimic avoids acoustic model differences. What sort of running time are you getting from that?

**Comment by daanzu** [comment]
Okay, everything should be working now. The test suite runs without errors for me on both windows and linux. Note that you need to upgrade to the latest version of KaldiAG: 2.1.0.

The other testing doesn't run dragonfly's test suite with generated audio instead of mimic (which I think works well), but rather is separate, to stress different parts of the backend, and as more of a integration test.

**Comment by daanzu** [comment]
Oh, I forgot to mention regarding testing: running the backend with generated audio via wave files can run very fast, if you disable the real time audio processing, thus allowing the engine to run at full speed.

**Comment by Danesprite** [comment]
I can confirm that my grammar works properly now and the test suite passes successfully. Thanks! I still get a few unrelated errors due to custom words that need to be added manually.

Ah, gotcha. Yes, this sort of additional integration testing is a good idea. It is possible to do this with the Sphinx back-end too.

Good to hear that Kaldi can do quick recognition from wave files. IIRC the Sphinx back-end `process_wave_file()` method always runs at full speed. The unstable natlink function `inputFromFile()` can also be configured to do this.

So this is ready to merge now?

**Comment by daanzu** [comment]
Yes, I think this should be ready for merging now, as far as I know, unless any other testers pipe up.

Re: testing with audio. True, for this, slowing of the processing down to real time is the code path that requires extra logic. The Kaldi backend supports both methods.

Re: custom words. They should be added automatically with estimated pronunciations. Is this not working for you?

**Comment by Danesprite** [comment]
Sorry for the late reply. I will merge this now.

It is good that Kaldi supports both processing methods. :-)

For custom words, I think there is just something wrong with my environment. The following doesn't normally work, but just worked when I tried it in a virtual environment:

```Shell
python3 -m kaldi_active_grammar add_word uncomment
```

**Comment by Danesprite** [comment]
There is some problem building the Kaldi engine class documentation which seems to be related to this PR. If you take a look at the [latest doc build](https://dragonfly2.readthedocs.io/en/latest/kaldi_engine.html#engine-api), you can see the KaldiEngine class does not appear. It does appear in the [stable doc build](https://dragonfly2.readthedocs.io/en/stable/kaldi_engine.html#engine-api) I set up today. That version is built using Dragonfly2 v0.30.1.

**Comment by daanzu** [comment]
@Danesprite It seems to build and look fine to me. Am I missing something?

**Comment by Danesprite** [comment]
@daanzu Huh. I'm not sure why it is building correctly now. Never mind then. Always nice when things magically fix themselves! :-)

**Pull request merged**
