### PR TITLE
Add Natlink retain support

### PR DESCRIPTION
**Pull request by daanzu**
This is shamefully completely untested, as I don't have DNS installed currently, but it looks right to me. It may be helpful for folks looking to prepare a data set for training another engine. Thanks to @dwks for the initial code.

### CODE REVIEW

**Comment by Danesprite** [comment]
Thanks! I'll check if this works.

**Comment by Danesprite** [comment]
This works fine apart from a slight mistake I just fixed.

Running Natlink normally, the current working directory will actually the directory where `natspeak.exe` is located (e.g. `C:\Program Files (x86)\Nuance\NaturallySpeaking15\Program`). This is because natlink is normally run from `natspeak.exe` (embedded). Given this unusual behaviour, I'm wondering whether we should only accept `retain_dir` if it is an absolute file path?

I will also mention that using `get_engine()` parameters for the Natlink engine won't work unless they are specified in a file that is loaded by natlink before any other Dragonfly modules, such as `_aaa.py`. If this is not done, then the `retain_dir` parameter will be ignored.

These problems don't apply to the natlink module loader I added to Dragonfly a few months ago, although only data for grammars loaded into that instance of `NatlinkEngine` will be retained. There are also other problems with using Natlink that way.

**Comment by Danesprite** [comment]
I've fixed these problems now. Relative `retain_dir` paths are now added onto the end of the Natlink user directory if `sys.executable` ends with `"natspeak.exe"`. The directory can now be set after engine initialization by using `engine.set_retain_directory()`.

I'll merge this now that these things are fixed. Thanks again @daanzu! :+1:

**Comment by daanzu** [comment]
Thanks for fixing this up to be usable!

**Pull request merged**
