### PR TITLE
Update to latest Kaldi 1.2.0

### PR DESCRIPTION
**Pull request by daanzu**
* **Improved Recognition**: better graph construction/compilation should give significantly better overall recognition.
* **Weights on Any Elements**: you can now easily add weights to any element (including compound elements in `MappingRule`s), in addition to any rule/grammar.
* **Pluggable Alternative Dictation**: you can optionally pass a `callable` as `alternative_dictation` to define your own, external dictation engine.
* **NOTE**: the default model directory is now `kaldi_model`.
* Various bug fixes & optimizations

I still need to add more documentation.

### CODE REVIEW

**Comment by Danesprite** [comment]
Thanks! I haven't done much testing yet, but I have noticed an error in the `mimic()` method. Apart from that it looks good :+1:

**Comment by Danesprite** [comment]
Fixed!

Did you want to add more documentation in this PR or later? I'm happy to merge it now. Should be able to release the changes in version 0.20.0 this weekend :-)

**Comment by daanzu** [comment]
Actually, hold off on merging for a day. I want to make one more change, to change the default model directory, in preparation for better models coming down the pipeline.

**Comment by Danesprite** [comment]
Sure thing. Let me know when it's ready.

**Comment by daanzu** [comment]
Okay, that should be good. I can finish the documentation later.

**Pull request merged**
