### PR TITLE
KaldiAG v0.7.1: Partial Decoding, Parallel Compilation, & Various Optimizations for 15-50% Speedup

### PR DESCRIPTION
**Pull request by daanzu**
* **Partial Decoding**: support for having **separate Voice Activity Detection timeout values** based on whether the current utterance is complex (dictation) or not.
* **Parallel Compilation**: when compiling grammars/rules that are not cached, multiple can be compiled at once (up to your core count).
    * Example: loading Caster without cache is ~40% faster (in addition to optimizations below).
* **Various Optimizations**: loading even while cached sped up 15%.
* Refactored temporary/cache file handling
* Various bug fixes

### CODE REVIEW

**Comment by Danesprite** [comment]
Thank! I have tried testing this on Linux, but I got the following error:

```
Traceback (most recent call last):
  File "kaldi_module_loader.py", line 101, in <module>
    main()
  File "kaldi_module_loader.py", line 92, in main
    engine.prepare_for_recognition()
  File "/home/dane/repos/dragonfly-daanzu/dragonfly/engines/backend_kaldi/engine.py", line 224, in prepare_for_recognition
    self._compiler.prepare_for_recognition()
  File "/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/compiler.py", line 368, in prepare_for_recognition
    self.compile_and_load_queue()
  File "/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/compiler.py", line 344, in compile_and_load_queue
    for kaldi_rule in results:
  File "/home/dane/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 641, in result_iterator
    yield fs.pop().result()
  File "/home/dane/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/home/dane/.local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/compiler.py", line 338, in <lambda>
    results = executor.map(lambda kaldi_rule: kaldi_rule.compile(lazy=False), self.compile_queue)
  File "/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/compiler.py", line 96, in compile
    self.compiler._compile_agf_graph(compile=True, nonterm=self.nonterm, input_data=fst_text, filename=self.filepath)
  File "/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/compiler.py", line 246, in _compile_agf_graph
    compile_command()
  File "/home/dane/.local/lib/python2.7/site-packages/ush.py", line 585, in __call__
    return wait(procs, raise_on_error)
  File "/home/dane/.local/lib/python2.7/site-packages/ush.py", line 189, in wait
    result = tuple(iterate_outputs(procs, raise_on_error, status_codes))
  File "/home/dane/.local/lib/python2.7/site-packages/ush.py", line 221, in iterate_outputs
    raise ProcessError(process_info)
ush.ProcessError: One or more commands failed: [(['/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/exec/linux/fstcompile', '--isymbols=kaldi_model_zamia/words.txt', '--osymbols=kaldi_model_zamia/words.txt'], 24920, 0), (['/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/exec/linux/compile-graph-agf', '--arcsort-grammar', '--grammar-prepend-nonterm=999995', '--grammar-append-nonterm=999996', '--nonterm-phones-offset=993', '--read-disambig-syms=kaldi_model_zamia/disambig.int', '--verbose=0', 'kaldi_model_zamia/tree', 'kaldi_model_zamia/final.mdl', 'kaldi_model_zamia/L_disambig.fst', '-', 'kaldi_model_zamia.tmp/8176d0a81e2395d2dade89f00795bdec815fb3cd.fst'], 24921, 255)]
```

KAG is up-to-date at version 0.7.1 and I'm using the most recent model and module loader scripts.

Any idea what may be causing this?

**Comment by daanzu** [comment]
Hmm, I will take a look.

**Comment by daanzu** [comment]
Ok, I fixed several bugs. Thanks to @Danesprite and @LexiconCode for the reports!

**Comment by Danesprite** [comment]
Thanks, this looks good to me now.

I noticed the Kaldi test suite fails with `SIGABRT` from the RPC `list_grammars` test method:

```
Verify that the 'list_grammars' RPC method works correctly. ... terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
[1]    18826 abort      python setup.py test --test-suite=dragonfly.test.suites.kaldi_suite
```

This does not occur with other engine test suites.

I'm happy to merge now if it's not a simple fix; I don't think anyone actually uses `dragonfly.rpc`.

**Comment by daanzu** [comment]
Yeah, I saw that but haven't been able to look into it yet. I wondered if it was something with my set up. I'd say go ahead and merge if it isn't going to affect anyone.

**Comment by Danesprite** [comment]
No problem. I'll merge this now and hopefully release version 0.17 tomorrow.

I just remembered that the RPC tests have broken for the Kaldi engine before: https://github.com/dictation-toolbox/dragonfly/pull/78#issuecomment-504863173 . Don't know if it's the same problem though.

**Pull request merged**
