### PR TITLE
Add support for special specifiers to Compound specs

### PR DESCRIPTION
**Pull request by daanzu**
Allows for adding attributes, either a specific value or just True. Must come at the end of a `Sequence`, and applies to that whole `Sequence` (or whatever more specific `Element`). The main impetus for this is easily specifying weights for Kaldi, but trying to making it flexible for future/other additions.

Examples:
* "alpha {weight=2}"
* "test <an_extra> [op] {test_special}"
* "foo | bar {test_special} | baz"

I am open to suggestions for the best implementation.

### CODE REVIEW

**Comment by Danesprite** [comment]
This is a good feature, thanks for adding it! I have noticed that optional specifier values are ignored for the second weights example. I've added some extra tests into `test_lark_parser.py` for testing that.

**Comment by Danesprite** [comment]
I guess to expand on my previous comment a bit: would it make sense to just allow any named special specifier, e.g. `"foo {foo} | bar {bar=2}"`? This would make the feature fairly flexible with what you could do with it.

**Comment by daanzu** [comment]
My thinking was: if we allow any specifier, it would be easy for typos to go unnoticed. Instead, when future specifiers are added, it would be easy to modify `parse.py` to allow them.

**Comment by daanzu** [comment]
It would also be a good place to make sure there are not clashing uses.

**Comment by Danesprite** [comment]
Those are good points. I'll change it back to only accept `w`, `weight` and `test_special`.

**Comment by daanzu** [comment]
Looks good to me!

**Comment by mrob95** [comment]
Looks good, and it's good to see that the lark parser allows these kinds of changes pretty painlessly 👍

**Comment by Danesprite** [comment]
Great, I'll merge this now then. Thanks again @daanzu!

@mrob95 It is good to see that yeah. These changes probably wouldn't have been easy with the old parser. Thanks again for that BTW :+1:. I'm still shocked at how quickly my grammars load now!

**Comment by daanzu** [comment]
Many thanks @mrob95! I had been wanting to add some stuff like this for a while, but wasn't looking forward to trying to shoehorn it in to the old parser.

**Pull request merged**
