### PR TITLE
Move internal lark parser grammar into parsing/parse.py

### PR DESCRIPTION
**Pull request by Danesprite**
CC @mrob95 

Re: #169, #170.

This grammar has been moved from the parsing/grammar.lark file, which has now been removed.  The grammar is used internally for parsing Compound element specifications efficiently.

This has been done because the file approach causes issues in some cases. It is also just simpler to have this grammar and the only code that uses it both in the same Python module.

### CODE REVIEW

**Comment by daanzu** [comment]
Good fix, thanks @Danesprite!

**Comment by Danesprite** [comment]
Thanks, though these changes are essentially the same as those in PR #169, by @mrob95.

I wonder if there might be similar problems with `dragonfly/engines/backend_kaldi/kag_version.txt`.

**Comment by daanzu** [comment]
@Danesprite Yes, `kag_version` has the same problem. What is your preferred solution for handling it?

**Comment by Danesprite** [comment]
@daanzu Okay then. The simplest solution would seem to be maintaining the required KAG version in both `setup.py` and `backend_kaldi/engine.py`. It is not as if it's updated regularly enough for this to cause problems.

**Comment by daanzu** [comment]
@Danesprite That makes sense; sounds good to me.

**Comment by Danesprite** [comment]
@daanzu Okay then. I'll make the necessary changes.

**Pull request merged**
