### PR TITLE
Kaldi v0.5.0: User Lexicon! Compilation Optimizations! Better Model!

### PR DESCRIPTION
**Pull request by daanzu**
Must use new model!

### CODE REVIEW

**Comment by daanzu** [comment]
Hold off on merging. There is a bug or 2 to fix.

**Comment by daanzu** [comment]
OK, there's still a weird bug with Unicode I haven't figured out yet preventing Caster from working, but all my other tests are working. Probably safe to merge.

**Comment by daanzu** [comment]
Unicode fixed.

**Comment by Danesprite** [comment]
Great! I'll do some testing on Linux.

**Comment by Danesprite** [comment]
So you have this working with Caster on Windows? That's pretty neat! How does it cope with the funny words?

I have done some testing and discovered two issues.

# Issue 1
Looking at the documentation, I tried adding a word to the user lexicon with the following commands:

```shell
# Works
python -m kaldi_active_grammar add_word cromulent

# After removing 'cromulent', this command doesn't add it properly.
python -m kaldi_active_grammar add_word cromulent "K R OW M Y UW L AH N T"

```

I have successfully matched words added to the lexicon via the first method or automatically (using `g2p_en`).

The second command produces the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/__main__.py", line 55, in <module>
    main()
  File "/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/__main__.py", line 45, in main
    phones = Model(args.model_dir).add_word(word, phones)
  File "/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/model.py", line 213, in add_word
    self.generate_lexicon_files()
  File "/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/model.py", line 242, in generate_lexicon_files
    generate_file('align_lexicon.int', lambda word, word_id, phones:
  File "/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/model.py", line 238, in generate_file
    file.write(write_func(word, word_id, phones) + '\n')
  File "/home/dane/.local/lib/python2.7/site-packages/kaldi_active_grammar/model.py", line 243, in <lambda>
    str_space_join([word_id, word_id] + [str(self.phone_to_int_dict[phone]) for phone in phones]))
KeyError: 'K_B'

```

I guess this a `kaldi_active_grammar issue`. I can make an issue over there if you like.

# Issue 2
I noticed a minor issue when testing with a `MappingRule` that had a `"<dictation>": ActionBase(),` mapping. Some commands in my grammar were being recognised as dictation instead. It was always the same words for some reason.

This isn't a big deal I suppose. I mainly use these mappings to stop Dragon from randomly typing prose into specific windows (e.g. games), but your Kaldi engine wouldn't do that. Just thought you should be aware of it because of the inconsistent behaviour.

**Comment by Danesprite** [comment]
Oh I forgot to mention that I tested this with my `X11Window` class. `AppContexts` work perfectly on Linux that way. They also work perfectly with the sphinx and text-input engines.

**Comment by daanzu** [comment]
I don't have Caster fully working yet, but it's progressing. The funny words should hopefully be handled automatically.

1. Oops, thanks for catching that regression. Fixed!

2. I actually do something similar while using WSR/Kaldi: I have a mode with a catch-all rule like that, which I can enable when working in a noisy environment, so only perfectly-matched recognitions occur. I then can also do that plus disabling normal keystroke/etc commands, so only a few application-specific commands plus the dictation no-op are enabled, and then I can even converse with people with the microphone on and only will there be a false positive.
Anyway, it's worked for me. Can you send me a minimal example where it happens, and/or debug logging?

And great to hear everything's working together!

**Comment by LexiconCode** [comment]
> 
> I don't have Caster fully working yet, but it's progressing. The funny words should hopefully be handled automatically.
> 
Yes as things progress I'll be evaluating the lexicon and making some optimizations Caster side to address the "Funnies" :)

**Comment by daanzu** [comment]
It'd also be easy to have a Caster add-on pack for the lexicon, with the pronunciations already added.

**Comment by Danesprite** [comment]
Okay then. A Caster add-on pack for the lexicon is a good idea!

Thanks for fixing the first issue. As for the second, it occurs with simple mapping rules like the following:

```Python
def text_func(text):
    print("Recognised '%s' as dictation." % text)


rule = MappingRule(
    mapping={
        "alpha": Key("a"),
        "bravo": Key("b"),
        "charlie": Key("c"),
        "<text>": Function(text_func),
    },
    extras=[Dictation("text")]
)

```

"bravo" is being matched as dictation for me, but "alpha" and "charlie" are not. I first noticed it with my OpenTTD grammar, which is more complex and uses `Repetition` elements a bit, if that makes a difference.

As it is a pretty obscure bug, I'm okay with merging this PR now if you think it might take a while to fix.

Your catch-all rule/mode sounds pretty useful! I have some macro buttons for toggling Dragon's microphone immediately from outside my Windows VM. Could probably get something similar working with sphinx, kaldi or WSR. That's what the `SphinxEngine.cancel_recognition()` method is for actually, but I'm not really sure how well it works.

**Comment by daanzu** [comment]
Ah, thanks, I replicated the dictation bug, and have an idea what's causing it. It'll take some work to fix, though. Up to you whether to merge now or wait a day or 3 to fix. BTW, it won't happen if you move the dictation to a separate rule in same grammar.

**Comment by Danesprite** [comment]
Okay then. I'd like to merge now and release version 0.15.0. The bug can be fixed in 0.15.1.

> BTW, it won't happen if you move the dictation to a separate rule in same grammar.

Thanks, good to know!

**Pull request merged**
