### PR TITLE
Kaldi Update

### PR DESCRIPTION
**Pull request by daanzu**
* The Caster "text manipulation" grammar fix may speed up all grammar compilation.
* Note the renaming of audio input parameter. Think it is okay?

@Danesprite What is your opinion on whether to throw an exception for a badly typed engine parameter, or just printing an error and setting to None?

@droundy Does this work for setting audio input by string? (#257)

### CODE REVIEW

**Comment by Danesprite** [comment]
> Note the renaming of audio input parameter. Think it is okay?

This is backwards-incompatible, which is annoying because it's a good idea. Perhaps just leave the old one in for the moment? I'd like to fix things like this in version 1.0.0 at some point.

We could also have separate methods based on what the [`Sapi5InProcEngine`](https://github.com/dictation-toolbox/dragonfly/blob/master/dragonfly/engines/backend_sapi5/engine.py#L363) does: `get_audio_sources()` and `select_audio_source()`. The latter method accepts device names/descriptions too.

> What is your opinion on whether to throw an exception for a badly typed engine parameter, or just printing an error and setting to None?

I think we have been somewhat inconsistent with this. I would say raise errors like it does at the moment, i.e. via "casts" like `float(...)`. Changing every Kaldi engine parameter to log errors instead would probably be annoying and not worth the hassle.

There is a sort of clash in Dragonfly between Python's dynamic typing system and associated best practices vs the static typing our SR engine back-ends use internally. I'm not really sure where the boundary should be between these 2 systems, apart from a vague sense of under `dragonfly.engines`. I don't know, maybe I'm over-thinking it.

**Comment by droundy** [comment]
Sounds good for the device setting. I wonder if it m adding the new parameter name, but leaving the old as an undocumented synonym would address the compatibility concern while moving forward with a better name?

**Comment by Danesprite** [comment]
Having `input_device_index` as a synonym argument sounds good to me.

**Comment by daanzu** [comment]
Thanks for the input. I'll make the synonym change.

Re typing: Yeah, and there's also the issue with dragonfly where it is frequently used in the background, where it is easy to miss error messages, and then not know why things aren't working as expected. Raising an exception is probably safer so it gets noticed.

**Comment by daanzu** [comment]
How does that look?

**Comment by Danesprite** [comment]
Looks good to me. Thanks! So this is ready to merge now?

**Comment by LexiconCode** [comment]
The grammar complexity for text manipulation is resolved from a number of reports and personal testing.

**Comment by daanzu** [comment]
@Danesprite I think it should be safe to merge. 👍

**Comment by Danesprite** [comment]
Okay then. :+1:

I'll release dragonfly2 version 0.26.0 with the new changes soon, hopefully tomorrow.

**Pull request merged**
