### PR TITLE
Clipboard toolkit additions, improvements and bug fixes

### PR DESCRIPTION
**Pull request by Danesprite**
CC @LexiconCode

This PR adds a `Clipboard.wait_for_change()` method and makes `Clipboard` instances comparable.

The `wait_for_change()` method is a blocking method which returns whether or not the system clipboard changed within a specified timeout period.

On Windows, this method compares clipboard sequence numbers.  On other platforms, it compares the clipboard contents.  Both of these implementations use polling.

It might be helpful to have an optional `formats` argument for this method. That way you can poll for changes to specific clipboard formats.

### CODE REVIEW

**Comment by LexiconCode** [comment]
> This PR adds a `Clipboard.wait_for_change()` method and makes `Clipboard` instances comparable.

This looks really nice thank you.

> It might be helpful to have an optional `formats` argument for this method. That way you can poll for changes to specific clipboard formats.

Yes I can see putting that the use if it's not inconvenient implement.

**Comment by LexiconCode** [comment]
Occasionally in some applications I get the following:

```
Clipboard Error: (1418, 'CloseClipboard', 'Thread does not have a clipboard open.')
<class 'pywintypes.error'>
(1418, 'CloseClipboard', 'Thread does not have a clipboard open.')
<traceback object at 0x22EF24C8>
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\context.py", line 143, in read_selected_without_altering_clipboard
    temporary = Clipboard(from_system=True).get_system_text()

  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\windows\base_clipboard.py", line 264, in __init__
    self.copy_from_system()

  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\windows\win32_clipboard.py", line 233, in copy_from_system
    win32clipboard.EmptyClipboard()

  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\Lib\contextlib.py", line 120, in __exit__
    next(self.gen)

  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\windows\win32_clipboard.py", line 90, in win32_clipboard_ctx
    win32clipboard.CloseClipboard()
```

```
def copy(pause_time):
    """
    Emulates copy shortcut on OS/Application context
    pause_time: key press delay in milliseconds
    """
    if sys.platform == "darwin":
        copy = Key("w-c:" + pause_time)
    else:
        copy = Key("c-c:" + pause_time)
    copy.execute()

def read_selected_without_altering_clipboard(same_is_okay=False, pause_time="20"):
    '''Returns a tuple:
    (0, "text from system") - indicates success
    (1, None) - indicates no change
    (2, None) - indicates clipboard error
    '''
    # Initialize with system clipboard content.
    try:
        cb = Clipboard(from_system=True)
        original = cb.get_system_text()
        
        # Use the system clipboard
        copy(pause_time)
        Clipboard.wait_for_change(timeout=1)
        temporary = Clipboard(from_system=True).get_system_text()
        # Restore original system clipboard content.
        cb.copy_to_system(True)

        if original == temporary and not same_is_okay:
            return 1, None
        return 0, temporary
    except Exception as e:
        print("Clipboard Error: " + str(e))  # 
        utilities.simple_log(None)
        return 2, None

**Comment by LexiconCode** [comment]
```
Execution of Paste('between ') failed due to exception: (1418, 'CloseClipboard', 'Thread does not have a clipboard open.')
Traceback (most recent call last):
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\actions\action_base.py", line 98, in execute
    if self._execute(data) is False:
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\actions\action_base.py", line 154, in _execute
    self._execute_events(self._events)
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\actions\action_paste.py", line 111, in _execute_events
    clipboard.copy_to_system()
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\windows\win32_clipboard.py", line 243, in copy_to_system
    win32clipboard.SetClipboardData(format, content)
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\Lib\contextlib.py", line 120, in __exit__
    next(self.gen)
  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\windows\win32_clipboard.py", line 90, in win32_clipboard_ctx
    win32clipboard.CloseClipboard()
pywintypes.error: (1418, 'CloseClipboard', 'Thread does not have a clipboard open.')
```
https://github.com/dictation-toolbox/Caster/blob/master/castervoice/lib/temporary.py#L66


```
def read_selected_without_altering_clipboard(same_is_okay=False, pause_time="20"):
    '''Returns a tuple:
    (0, "text from system") - indicates success
    (1, None) - indicates no change
    (2, None) - indicates clipboard error
    '''
    # Initialize with system clipboard content.
    try:
        cb = Clipboard(from_system=True)
        original = cb.get_system_text()
        
        # Use the system clipboard
        copy(pause_time)
        cb.wait_for_change(timeout=1)
        temporary = cb.get_system_text()
        # Restore original system clipboard content.
        cb.copy_to_system(True)

        if original == temporary and not same_is_okay:
            return 1, None
        return 0, temporary
    except Exception as e:
        print("Clipboard Error: " + str(e))  # 
        utilities.simple_log(None)
        return 2, None 
```

**Comment by Danesprite** [comment]
> Yes I can see putting that the use if it's not inconvenient implement.

Okay then, I'll add that in. It is not too difficult to implement. I think it will be more useful on X11, both as a performance measure (fewer subprocesses) and to ignore changes to the PRIMARY X selection, which is typically used to select text and paste it with the middle mouse button. Or, it could be used for only checking the PRIMARY selection.

The `CloseClipboard()` error you're getting occurs when `win32_clipboard_ctx()` is used more than once. I just need to adjust it to catch errors raised by `CloseClipboard()`. The `wait_for_change()` method doesn't open the clipboard on Windows. I'll fix this bug separately.

**Comment by Danesprite** [comment]
All done now. The `formats` argument works with all three implementations.

It turned out to be a too tricky to use fewer xsel subprocesses on X11. The best thing would be to implement `BaseX11Clipboard` using PythonXLib instead, but this works okay. The `step` argument can always just be increased a bit.

I have just fixed the `CloseClipboard()` bug on this branch after all. Only Windows error 1418 is caught.

**Comment by LexiconCode** [comment]
The issue regarding `CloseClipboard()` is resolved.  Thank you for another great addition!

**Comment by LexiconCode** [comment]
hmmm I'm still getting some errors. `pip install git+https://github.com/dictation-toolbox/dragonfly.git@feat/wait-for-clipboard-change`

These errors are sporadic.It seems like there must be sort of timing a race condition happening between the clipboard methods and the paste action however `read_selected_without_altering_clipboard` should be complete before `Retrieve(ActionBase):` which utilizes the paste action. 

`Could not retrieve clipboard data for format 'Chromium Web Custom MIME Data Format': (1418, 'GetClipboardData', 'Thread does not have a clipboard open.')`
and
```
Clipboard Error: Specified clipboard format is not available
<class 'TypeError'>
Specified clipboard format is not available
<traceback object at 0x231C9F68>
  File "D:\Backup\Library\Documents\Caster\castervoice\lib\context.py", line 143, in read_selected_without_altering_clipboard
    temporary = Clipboard(from_system=True).get_system_text()

  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\windows\base_clipboard.py", line 288, in __init__
    self.copy_from_system()

  File "C:\Users\Main\AppData\Local\Programs\Python\Python38-32\lib\site-packages\dragonfly\windows\win32_clipboard.py", line 257, in copy_from_system
    content = win32clipboard.GetClipboardData(format)
```

is the paste action [Paste()](https://github.com/dictation-toolbox/Caster/blob/master/castervoice/lib/temporary.py#L66) contributing to this issue? 

In the particular `convert to integer`

**Comment by LexiconCode** [comment]
Here's a dragonfly rule `test brax` command to reproduce the issue.

[_test_rule.zip](https://github.com/dictation-toolbox/dragonfly/files/6556884/_test_rule.zip)

**Comment by Danesprite** [comment]
Yes, I think you're right about that. I'll adjust the `Win32Clipboard` methods that change the system clipboard to wait a bit for a new sequence number before returning.

I think the first error is another issue with `win32_clipboard_ctx()` where nested calls can close the clipboard too early.

**Comment by LexiconCode** [comment]
'''Execution of Paste('[test]') failed due to exception: (1418, 'SetClipboardData', 'Thread does not have a clipboard open.')
Traceback (most recent call last):
  File "C:\Users\MainLaptop\AppData\Local\Programs\Python\Python39\lib\site-packages\dragonfly\actions\action_base.py", line 98, in execute
    if self._execute(data) is False:
  File "C:\Users\MainLaptop\AppData\Local\Programs\Python\Python39\lib\site-packages\dragonfly\actions\action_base.py", line 154, in _execute
    self._execute_events(self._events)
  File "C:\Users\MainLaptop\AppData\Local\Programs\Python\Python39\lib\site-packages\dragonfly\actions\action_paste.py", line 111, in _execute_events
    clipboard.copy_to_system()
  File "C:\Users\MainLaptop\AppData\Local\Programs\Python\Python39\lib\site-packages\dragonfly\windows\win32_clipboard.py", line 290, in copy_to_system
    win32clipboard.SetClipboardData(format, content)
pywintypes.error: (1418, 'SetClipboardData', 'Thread does not have a clipboard open.')'''
or

As stress test back to back
```
sleep(3)
enclose_selected("[~]")
enclose_selected("[~]")
```


```
[test]
[]
Could not retrieve clipboard data for format 'text': (1418, 'GetClipboardData', 'Thread does not have a clipboard open.')
Could not retrieve clipboard data for format 'oemtext': (1418, 'GetClipboardData', 'Thread does not have a clipboard open.')
```

**Comment by Danesprite** [comment]
Thanks for these. As we discussed privately, these errors seem to be happening with specific applications. It is something we cannot fix.

I have adjusted the context manager again to not catch errors from `CloseClipboard()`, since these can no longer be caused by nested calls, which probably wasn't happening here any way.

I'm not sure of the best way to handle, as discussed, optional verification of sequence number changes before returning from methods that change the system clipboard. Perhaps an optional `current_sequence_number` argument for `wait_for_change()` that only works on Windows?

**Comment by Danesprite** [comment]
@LexiconCode Aside from the missing documentation for `synchronized_changes()`, do you think this is ready to be rebased and merged? Have you found any issues?

**Comment by LexiconCode** [comment]
> 
> 
> @LexiconCode Aside from the missing documentation for `synchronized_changes()`, do you think this is ready to be rebased and merged? Have you found any issues?


```python
with Clipboard.synchronized_changes(timeout=2):
    Key("c-c").execute()
text = Clipboard.get_system_text()
```

`Traceback (most recent call last):
  File "c:\Users\Main\Desktop\_test_rule.py", line 6, in <module>
    with Clipboard.synchronized_changes(timeout=2):
AttributeError: type object 'Win32Clipboard' has no attribute 'synchronized_changes'`

**Comment by Danesprite** [comment]
Hmm. I can't replicate this. Are you sure it is the right branch?

**Comment by LexiconCode** [comment]
> 
> 
> Hmm. I can't replicate this. Are you sure it is the right branch?

Hmm weird the autocomplete/goto definition picked it up the first time. Reinstalling resolved Attribute Error.

**Comment by LexiconCode** [comment]
@Danesprite 

Regarding other applications Typora and games. This issue is directly related to how dragonfly initiates keys. When a key is virtually pressed it does so instantly. 

Some applications expect a delay in keyboard input. In Typora 'sleep(50/1000.)' and the key presses work as expected. 

Here's the strange thing for Typora. This isn't needed between each key press but only at the beginning of an action series. In this case the beginning action is 'Key(c-c)'.


Now this is partially solved by having an outer pause Key(c-c:xx) but that does not solve the inter pause. In the dragonfly repository as currently implemented users would require a sleep/pause action at the beginning of all actions.

**Comment by LexiconCode** [comment]
Looks good to go!

**Comment by Danesprite** [comment]
Ah, thanks for clearing that up. :+1:

**Comment by Danesprite** [comment]
Okay, all done. Sorry this change-set has taken me a while to finalise. Thanks for your help in putting this together and testing it. :-)

**Pull request merged**
