### PR TITLE
Kaldi backend updates

### PR DESCRIPTION
**Pull request by daanzu**
I changed the audio to use a different python package, which should be better, cleaner, and not require compilation for installation. However, although it has been working well for me, it could probably use some testing by others.

I have other improvements that should be ready soon for the next version.

### CODE REVIEW

**Comment by daanzu** [comment]
Updated package version with some fixes:

* `time.clock()` deprecation
* fix for hung compiling on some ambiguous grammars (as a bonus, may speed up all compilation)

**Comment by daanzu** [comment]
Oh, and MacOS support! 🎉

**Comment by Danesprite** [comment]
I've rebased this branch, as it was a bit out of date, and have done some testing on each platform.

It's all working nicely from my manual testing. I'm getting two doctest errors when running the test suite on macOS with Python 2.7 and 3.7:

* test_grammar_list_doctest.txt
* test_recobs_doctest.txt

I can post the `ProcessError` tracebacks here, but they are pretty long. Let me know if you can't reproduce them. I'm using the Zamia model BTW.

**Comment by daanzu** [comment]
@Danesprite Thanks, I will take a look.

**Comment by daanzu** [comment]
@Danesprite Can you give me a bit more info on the errors you are getting? I am getting 12 failed, 37 passed, 1 warnings running in Python3.7, but at a quick glance, they seem to be outside of Kaldi: a bunch of apple script errors in `darwin_window.py` that I know nothing about.

**Comment by Danesprite** [comment]
Sorry for the delay! I don't get any Apple Script errors when I run the tests. I guess maybe there is a version difference between us?

I've attached a file with my test output. Hopefully you can make sense of it :-)

[test_output.txt](https://github.com/dictation-toolbox/dragonfly/files/4311395/test_output.txt)

**Comment by daanzu** [comment]
Can you try running with the `-s` option to show stderr? Setting `kaldi.compiler` logging level to `10` may also be informative. The tests work in linux for you, right?

**Comment by Danesprite** [comment]
Okay then. I have attached the updated test output. I have also included stderr this time.

And yes, the tests do work for me on linux. No test failures.

[test_output.txt](https://github.com/dictation-toolbox/dragonfly/files/4315118/test_output.txt)

**Comment by LexiconCode** [comment]
Should the dependency for x11 be included?

**Comment by Danesprite** [comment]
Do you mean psutil? Yeah, that should be removed.

**Comment by Danesprite** [comment]
I've removed psutil from the macOS dependency list on the master branch.

**Comment by daanzu** [comment]
Hmm. Puzzling. I will try some more to try to replicate it locally so I can debug in detail.

By the way, is there an easy way to set logging levels for during running tests?

**Comment by daanzu** [comment]
@Danesprite Actually, if you could rerun the tests as you did but with `kaldi.compiler` logging set to `1`, it might give me enough information to reproduce it even if I can't fix my other problem.

**Comment by LexiconCode** [comment]
@Danesprite I was thinking on Linux.

**Comment by Danesprite** [comment]
@daanzu No, unfortunately there is no easy way to configure that. I have been adjusting the logging levels in `dragonfly/log.py`. I've attached the new output: [test_output.txt](https://github.com/dictation-toolbox/dragonfly/files/4315876/test_output.txt).

@LexiconCode I'm not sure what you mean. Do you mean that an X11 environment should be required if using Dragonfly on Linux?

**Comment by LexiconCode** [comment]
That's correct I don't think it's a requirement.

**Comment by LexiconCode** [comment]
Testing it looks like to me it's still trying to import pyaudio.

https://github.com/dictation-toolbox/dragonfly/blob/4967ea4d49cecdfe61b2037a0884bff857ac8073/dragonfly/engines/backend_kaldi/engine.py#L73

**Comment by Danesprite** [comment]
I don't think explicitly requiring X11 on Linux would be a good idea. This would break our test build, but more than that, X11 is not really even a requirement on Linux or other systems. It's just that certain functionality won't work in other environments, e.g. keyboard/mouse input in Wayland or a virtual console.

Thinking about it, this should be clearer in the README and in the documentation. I'll make some changes in #212.

**Comment by LexiconCode** [comment]
Okay that makes sense, thanks for clarifying.

**Comment by Danesprite** [comment]
@LexiconCode No worries!

@daanzu I'm happy to just merge this now BTW; these are problems that could just be solved later, most things work perfectly.

**Comment by daanzu** [comment]
@Danesprite Sure, it is probably better to go ahead and merge this and get it out there, while I try to figure out whatever crazy thing is going on in the tests. 👍

**Comment by Danesprite** [comment]
Okay then. Sounds good :+1:

**Pull request merged**
