### PR TITLE
Rework Pocket Sphinx engine backend

### PR DESCRIPTION
**Pull request by Danesprite**
I've finally managed to finish most of my planned Pocket Sphinx engine rework.

The notable changes are:
- Disable support for Dictation elements (temporarily). This allowed me to make the other changes.
- Disable writing training data to files by default.
- Greatly simplify GrammarWrapper and engine classes.
- Implement less buggy JSGF compiler classes and remove dragonfly2jsgf.
- Make all built-in key phrases optional in engine configuration.
- Optimise rule activation/deactivation and speech matching process.
- Rewrite/remove/relocate lots of unit tests.

### TODO

- [X] Fix engine module loader
- [x] Use single-threaded timer manager class with the engine.
- [X] Change `TrainingDataWriter` to write to files at the end of utterances to avoid writing empty files.
- [X] Change recognition loop to use a streamer class and thread to minimise dropped audio frames.
- [X] Update engine documentation page to reflect the changes.
- [X] Check if the engine is connected in all relevant public engine methods using `if self._decoder`.

#### Dictation-related
- Fix a few problems with the *pyjsgf* DictationGrammar class and release a new version.
- Re-implement Dictation element support using a simpler, single-threaded approach.
- Adjust (and simplify) dictation tests in *test_engine_sphinx_dictation.py* appropriately.

#### Other
- Release *sphinxwrapper* on PyPI and remove Git sub-module.

### CODE REVIEW

**Comment by Danesprite** [comment]
I think it might be better to merge this without support for Dictation elements and add that back in later. As it stands this rework is significantly more functional than the current version. The code is also much easier to understand.

I'd still like to get some of the tasks done before merging. I'll update the to-do list and add a few other things I've noticed.

**Comment by LexiconCode** [comment]
Fantastic work!

**Comment by Danesprite** [comment]
Some more big changes and additions, some I didn't plan to make:
- Add *sphinx_wave_transcriber.py* example script in the *dragonfly/examples* folder for using `engine.process_wave_file()`.
- Add sphinx engine `default_search_result` property.
- Allow specifying search options in the decoder config other than "-lm".
- Change `engine.process_wave_file()` method to return a list of results.
- Change sphinx engine to allow spaces to be used in grammar, rule, list and reference names.
- Disable built-in key phrases if the engine language isn't English.
- Fix a few bugs, including one that caused segmentation faults from Pocket Sphinx on list updates.
- Make engine configuration optional with defaults.
- Remove engine's *config.py* file.
- Replace *PYAUDIO_STREAM_KEYWORD_ARGS* with 4 new engine config options: *RATE*, *CHANNELS*, *SAMPLE_WIDTH*, *FRAMES_PER_BUFFER*.

Just the timer implementation and *sphinxwrapper* distribution left now. The latter may take me a while, so I think this should be merged before that.

**Comment by Danesprite** [comment]
All done now! Timers will only run when audio is processed with the `process_buffer()`, `process_wave_file()` or `recognise_forever()` engine methods. Also fixed some other things.

Normal threads can actually be used instead of timers because there aren't any unusual multi-threading limitations with the sphinx engine.

I've added these details into the relevant documentation pages. I'll open up an issue for adding `Dictation` support back in later. Ready for merging now! 🎉

**Pull request merged**
