### PR TITLE
Kaldi update

### PR DESCRIPTION
**Pull request by daanzu**
The big change here is preliminary support for better confidence information. I am pushing this now so that I can get some feedback on how useful the numbers are for folks.

To test, please run with logging turned on and `logging.getLogger('kaldi.wrapper').setLevel(9)` and `logging.getLogger('engine').setLevel(12)`. Make sure to update the kaldi-active-grammar package. There are two measures to observe:

* EER (expected error rate): lower is better
* confidence: higher is better

It would be very helpful to get feedback on whether either or both measures have a good threshold value for utterances that should be considered good or bad. Thanks!

(I also included a minor convenience function here rather than making a whole branch for it. I hope you don't mind?)

### CODE REVIEW

**Comment by caspark** [comment]
@daanzu I tried testing this; I bumped kaldi-active-grammar to 1.5.0, did `pip install git+https://github.com/daanzu/dragonfly.git#egg=dragonfly2` and set log levels of

```
    logging.getLogger("kaldi.wrapper").setLevel(9)
    logging.getLogger("engine").setLevel(12)
```

I tested mostly with dictation. I'm not sure what the thresholds are set to currently.

For me it seems like when SLC is 2 or greater and WER is < 0.6 or so then Kaldi pretty much always got it right (or "as good as dragon"). So I think the false positive rate is pretty good. There was only one case where I noticed that it was way off and that was when Kaldi heard a gibberish command sequence when I spoke dictation yet it thought had high SLC and low WER. I could not repro that though (I could get Kaldi to recognize the commands incorrectly but each time after the first the SLC was low and WER was high).

The false negatives might need some more tweaking though:

1. I did some testing with longer dictations (20ish words) and it was quite hard to beat the thresholds I suggested above, even though Kaldi heard it just as well as the shorter dictations).
2. It seems like when the language model is violated (?) the confidence goes down and error go up. For example this dictation would always "fail" my thresholds even though Kaldi gets it close enough that I'd be happy with its recognition here:

> The accountant will then add another transaction transferring one thousand dollars from account A to account B as they originally intended.

and that's recognised as this (sing is my "uppercase first letter" dictation command):

> sing the accountant will then add another transaction transferring one thousand dollars from county to account be as they originally intended

so that's pretty good, but it only scored SLC 0.585938 / WER 1.39679, which is quite bad. Here's the log output just in case.

```
kaldi.wrapper (Level 15): decoded at 0.14 RTF, for 6480 ms audio, spending 886 ms, of which 20 ms (2%) in finalization
kaldi.wrapper (Level 13):     decode times: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 15 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 12 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 17 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 18 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 31 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 47 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 56 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 13 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 11 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 25 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 12 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 10 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 16 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 126 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 24 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 13 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 60 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 17 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 13 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 30 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 51 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 13 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 47 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 42 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 26 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 16 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 24 0 0 0 20
LOG ([5.5-win]:dragonfly::AgfNNet3OnlineModelWrapper::GetDecodedString():dragonfly\agf-nnet3.cc:697) SLC(2paths): 0.585938
LOG ([5.5-win]:dragonfly::AgfNNet3OnlineModelWrapper::GetDecodedString():dragonfly\agf-nnet3.cc:698)     1st best: #nonterm:rule3 sing #nonterm:dictation the accountant will then add another transaction transferring one thousand dollars from county to account be as they originally intended #nonterm:end #nonterm:end
LOG ([5.5-win]:dragonfly::AgfNNet3OnlineModelWrapper::GetDecodedString():dragonfly\agf-nnet3.cc:699)     2nd best: #nonterm:rule3 sing #nonterm:dictation the accountant will then add another transaction transferring one thousand dollars from county to account b as they originally intended #nonterm:end #nonterm:end
VLOG[1] ([5.5-win]:ExecutionTimer::stop():dragonfly\utils.h:32) ExecutionTimer: Completed confidence in 2099 microseconds
LOG ([5.5-win]:dragonfly::AgfNNet3OnlineModelWrapper::GetDecodedString():dragonfly\agf-nnet3.cc:712) MBR(SER): 1.39679 : #nonterm:rule3 sing #nonterm:dictation the accountant will then add another transaction transferring one thousand dollars from county to account be as they originally intended #nonterm:end #nonterm:end
VLOG[1] ([5.5-win]:ExecutionTimer::stop():dragonfly\utils.h:32) ExecutionTimer: Completed expected_ser in 1119 microseconds
LOG ([5.5-win]:dragonfly::AgfNNet3OnlineModelWrapper::GetDecodedString():dragonfly\agf-nnet3.cc:725) MBR(WER): 1.39679 : #nonterm:rule3 sing #nonterm:dictation the accountant will then add another transaction transferring one thousand dollars from county to account be as they originally intended #nonterm:end #nonterm:end
VLOG[1] ([5.5-win]:ExecutionTimer::stop():dragonfly\utils.h:32) ExecutionTimer: Completed expected_wer in 1078 microseconds
VLOG[1] ([5.5-win]:ExecutionTimer::stop():dragonfly\utils.h:32) ExecutionTimer: Completed compare mbr in 1252 microseconds
VLOG[1] ([5.5-win]:ExecutionTimer::stop():dragonfly\utils.h:32) ExecutionTimer: Completed expected_error_rate in 856 microseconds
Recognized: sing the accountant will then add another transaction transferring one thousand dollars from county to account be as they originally intended
```

**Comment by daanzu** [comment]
@caspark Thanks for the detailed info! Very helpful!

Thoughts:

* For those SLC & WER values, do you think a logical OR or AND should be used? Or do you think one is strictly better than the other?
* Perhaps we only need the threshold for non-dictation commands? (It is hard for language model to know everything.)
* Perhaps we only need the threshold for utterances under a certain length? (It seems like many/most bad recognitions are short?)

**Comment by Danesprite** [comment]
Sorry I've taken a while to respond to you on this. This all looks good to me. I will do some testing of the thresholds and get back to you.

> (I also included a minor convenience function here rather than making a whole branch for it. I hope you don't mind?)

No worries, that convenience function looks quite useful.

**Comment by droundy** [comment]
From my perspective this sounds mostly useful for non dictation commands. When I do dictation I expect whatever the best guess is, and can edit any mistakes.  But I really don't want my computer issuing random commands the only vaguely resemble what I asked it to do.

I haven't tried this yet. Will I need an updated version of dragonfly2 to do this test? I got a link directly to this page and am unclear if it is a pull request that hasn't been merged, or how to install a version that supports this.

**Comment by shervinemami** [comment]
I'll give it a try this weekend.

**Comment by LexiconCode** [comment]
> I haven't tried this yet. Will I need an updated version of dragonfly2 to do this test? I got a link directly to this page and am unclear if it is a pull request that hasn't been merged, or how to install a version that supports this.

It is not been merged yet as it's considered draft. Ast the top of the page you should see `daanzu:kaldi`
image
Clicking on that should take you to the branch that you can download the zip and install manually with `python -m pip install -e .[kaldi]`

**Comment by caspark** [comment]
@droundy @LexiconCode fwiw you can avoid the zip download step by doing `pip install git+https://github.com/daanzu/dragonfly.git#egg=dragonfly2` as I mentioned in my initial comment. Make sure to update kaldi-active-grammar too though.

Re testing this again, sorry, this fell off my radar for a bit so I haven't tested again to see if my suggested thresholds make sense for pure command utterances. I agree that it's probably most useful to use this for commands as you suggested. Although, most utterances with some dictation will include at least one command word usually (e.g. to choose the formatting of the dictation), so really I mean "most useful to use it for utterances without dictation".

But that makes me think - would we really want "accidentally recognizing a dictation" to make us not pay attention to the confidence levels? The command that triggers a dictation could have had very low confidence, for example. Can we break out the confidence by word or by "segment of dictation/non-dictation" to avoid that, and only pay attention to the confidence assigned to command words/segments?

**Comment by daanzu** [comment]
@caspark No problem. Thanks for the feedback!

I think it is theoretically possible to "break out" the command segment and only compute the confidence for it, but that would require some sizable additional implementation. Perhaps a good phase two.

**Comment by shervinemami** [comment]
I did a little bit of testing with command mode. I feel that SLC seems slightly more reliable for me than MBR.
When I speak very clearly, it usually shows up as:
```
SLC(1paths): inf
MBR(WER): 0
```
But occasionally values such as:
```
SLC(2paths): 2.81789
MBR(WER): 0.0645411
```
Or:
```
SLC(2paths): 4.10609
MBR(WER): 0.0405764
```

Here is an example of a time it made a misrecognition. My grammar includes the words "endy", "homey" and "bony". Here is an example where I said the word "endy" but it got recognized as "homey" with this output:
```
LOG ([5.5.754-9751e9]:GetDecodedString():agf-nnet3.cc:697) SLC(2paths): 1.44597
LOG ([5.5.754-9751e9]:GetDecodedString():agf-nnet3.cc:698)     1st best: #nonterm:rule17 homey #nonterm:end
LOG ([5.5.754-9751e9]:GetDecodedString():agf-nnet3.cc:699)     2nd best: #nonterm:rule17 endy #nonterm:end
LOG ([5.5.754-9751e9]:GetDecodedString():agf-nnet3.cc:712) MBR(SER): 0.195221 : #nonterm:rule17 homey #nonterm:end
LOG ([5.5.754-9751e9]:GetDecodedString():agf-nnet3.cc:725) MBR(WER): 0.195221 : #nonterm:rule17 homey #nonterm:end
```
So in this example, SLC is more suited to a threshold of around 2.0 like caspark mentioned. (PS: I have the retained wav file of this specific example, if you want).

I definitely saw times when SLC was 5 or 6 even though I purposely said something ambiguous, and also times when SLC was 0.5 or 1 even though I tried to speak clearly. So I'm not sure if having a threshold for recognition is ideal, but I do get the impression that I would like it (having a threshold of SLC >= 2 otherwise the recognition fails).

LOG ([5.5.754-9751e9]:GetDecodedString():agf-nnet3.cc:697) SLC(2paths): 4.34041
LOG ([5.5.754-9751e9]:GetDecodedString():agf-nnet3.cc:698)     1st best: #nonterm:rule17 homey #nonterm:end
LOG ([5.5.754-9751e9]:GetDecodedString():agf-nnet3.cc:699)     2nd best: #nonterm:rule17 bony #nonterm:end
VLOG[1] ([5.5.754-9751e9]:stop():utils.h:32) ExecutionTimer: Completed confidence in 105 microseconds
LOG ([5.5.754-9751e9]:GetDecodedString():agf-nnet3.cc:712) MBR(SER): 0.0484534 : #nonterm:rule17 homey #nonterm:end
VLOG[1] ([5.5.754-9751e9]:stop():utils.h:32) ExecutionTimer: Completed expected_ser in 57 microseconds
LOG ([5.5.754-9751e9]:GetDecodedString():agf-nnet3.cc:725) MBR(WER): 0.0484534 : #nonterm:rule17 homey #nonterm:end
VLOG[1] ([5.5.754-9751e9]:stop():utils.h:32) ExecutionTimer: Completed expected_wer in 38 microseconds
VLOG[1] ([5.5.754-9751e9]:stop():utils.h:32) ExecutionTimer: Completed compare mbr in 29 microseconds
VLOG[1] ([5.5.754-9751e9]:stop():utils.h:32) ExecutionTimer: Completed expected_error_rate in 27 microseconds

**Comment by daanzu** [comment]
@shervinemami Thanks for the info!

**Comment by shervinemami** [comment]
@daanzu  Do you want me to upload these 2 specific wav files with incorrect command recognitions of "endy"? Or is it more useful to look at overall stats across lots of examples? I think with a bit of changes to [https://github.com/shervinemami/practice_speechrec_mappings](https://github.com/shervinemami/practice_speechrec_mappings) I can quickly generate hundreds of examples of SLC & WER for both the correct and incorrect command recognitions if you want.

**Comment by daanzu** [comment]
@shervinemami No thanks, I think I am good for now. I will try to get a basic threshold posted soon to try out and we can see how it works in practice.

**Comment by daanzu** [comment]
Okay, I added a threshold `expected_error_rate_threshold`, above which commands won't be processed, but anything with dictation will. Give it a try and let me know how it works.

```
engine = get_engine("kaldi", expected_error_rate_threshold=0.1)
```

**Comment by shervinemami** [comment]
Nice, thanks David! I'm busy at the moment but I've set a reminder for myself in about 2 weeks time to modify Dragonfly so the recognition failure callback allows an optional parameter, showing if the recognition failed due to the confidence being below the threshold. That way once I start playing with the threshold feature, I'll be aware of when the threshold was applied and when it wasn't. (I use recognition observer in a system tray notification showing me my successful & failed recognitions all day while I'm talking).

**Comment by Danesprite** [comment]
@daanzu Sorry I haven't tested this yet. I'll try to do it soon. I noticed you have exposed Kaldi recognition results :+1:

**Comment by daanzu** [comment]
@Danesprite @shervinemami No problem. I went ahead and marked this ready, assuming no issues pop up.

**Comment by JohnDoe02** [comment]
@daanzu I just tried the value you suggested above, i.e., `expected_error_rate_threshold=0.1`. However it turned out I got problems depending on my context.

This is from my retain.tsv:
```
retain_2020-07-09_17-22-19_448270.wav  0.96    ccr rule        ccr vim rules   super ticky     0.5196368098258972              False
retain_2020-07-09_17-22-20_664323.wav  0.88    ccr rule        default_rule    super ticky     0.02247561514377594             False
```

With a value of `0.1` the command `super ticky` wouldn't be recognized within vim (where my grammar is more rich), but in the default context it would.

I will continue to play around with other values, maybe something like `1.0` works better for most of my contexts.

**Comment by daanzu** [comment]
@JohnDoe02 Thanks for testing!

Actually, there is an issue that I don't think I have mentioned here: if you have multiple, redundant paths of recognition through separate rules, the estimate can go way up (because it can't decide which rule to pick). I have already fixed this in my development branch, and hope to release it in the next version in a few days. But I don't think this occurs often in practice? And I don't know whether this is affecting your case. (You can tell if it is by enabling the debugging logging and seeing if the second best guess is the same words except a different rule number.)

**Comment by JohnDoe02** [comment]
i can confirm now that differences in the error rates stem from multiple rules being active:

```
LOG ([5.5.779~1-db0af]:GetDecodedString():agf-nnet3.cc:698)     1st best: #nonterm:rule7 super ticky #nonterm:end
LOG ([5.5.779~1-db0af]:GetDecodedString():agf-nnet3.cc:699)     2nd best: #nonterm:rule7 super air ticky #nonterm:end
LOG ([5.5.779~1-db0af]:GetDecodedString():agf-nnet3.cc:712) MBR(SER): 0.00707973 : #nonterm:rule7 super ticky #nonterm:end
```
vs.
```
LOG ([5.5.779~1-db0af]:GetDecodedString():agf-nnet3.cc:698)     1st best: #nonterm:rule7 super ticky #nonterm:end
LOG ([5.5.779~1-db0af]:GetDecodedString():agf-nnet3.cc:699)     2nd best: #nonterm:rule4 super ticky #nonterm:end
LOG ([5.5.779~1-db0af]:GetDecodedString():agf-nnet3.cc:712) MBR(SER): 0.506963 : #nonterm:rule7 super ticky #nonterm:end
```

**Comment by daanzu** [comment]
@JohnDoe02 Ah, good, then that should be fixed soon. Yeah, the compiled package (the fix is in the Kaldi binary) isn't up to date. I hope to have it posted this weekend.

**Comment by daanzu** [comment]
@JohnDoe02 New version released and pushed. Make sure to upgrade to the new version of kaldi-active-grammar (1.6.0).

**Comment by ileben** [comment]
I have just updated kaldi-active-grammar to 1.6.0, then I tried to install these latest fixes by running:
`python -m pip install --upgrade --force-reinstall git+https://github.com/daanzu/dragonfly.git#egg=dragonfly2`

On start up I now get a crash in fstcompile with this error:
`The code execution cannot proceed because VCRUNTIME140_1.dll was not found.`

**Comment by daanzu** [comment]
@ileben Hmm, the new builds are from VC2019. I will look into it, but this may fix it: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads, specifically https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by ileben** [comment]
@daanzu I have visual studio 2017 installed on this machine, but not 2019. Could you package the redistributable along with the executable or have pip install it somehow? I am really not that familiar with python distribution methods.

**Comment by daanzu** [comment]
@ileben I'm not sure that there is a great way to handle it in python, but it is usually installed with many applications. You just need to download (15MB) and run: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by ileben** [comment]
@daanzu Yep, I know. I'm just turning to figure out how this could be done better. Otherwise the setup instructions should be updated, as well as the setup instructions and/or install scripts for Caster etc

**Comment by Danesprite** [comment]
I have (finally) done some testing of this. The error rate and confidence measures look good to me. I've fixed a bug I noticed when setting `expected_error_rate_threshold` via Dragonfly's CLI.

Code-wise this PR looks ready to me. The documentation needs to be updated though. The Kaldi doc page and some docstrings should include information on the new features, arguments, etc introduced in this PR. Some things that stand out:

* New arguments like `expected_error_rate_threshold` and `retain_approval_func` need to be documented.
* As the `AudioStore` class has a docstring, perhaps it should be included at the end of the Kaldi doc page?
* The new `Recognition` results object class should have a description and be referenced to in [this section](https://dragonfly2.readthedocs.io/en/latest/grammar.html#recognition-callbacks-with-results-objects).

I can handle the 2nd two.

**Comment by daanzu** [comment]
@Danesprite Thanks for the testing and fixes! Sounds good. I will add documentation for the engine parameters, and let you add the other two (so I don't have to re-learn how inter-document RST works 😉).

**Comment by Danesprite** [comment]
I've done the second point with the inter-document RST part. I usually also have to look up how that works 😄. The `Recognition` class could be updated further, but that can wait.

On second thought, I don't think `AudioStore` should be really be included in the documentation. The docstring is useful for issue #196 though.

**Comment by daanzu** [comment]
Yeah, `AudioStore` is probably too internal.

However, I'm not sure how to correctly link to the documentation for `AudioStoreEntry` when describing `retain_approval_func`. Could you take a look?

Otherwise, I think this is ready?

**Comment by Danesprite** [comment]
Sure, I can do that for you. Other than that, I agree this is ready :+1:

**Comment by Danesprite** [comment]
Done. I also fixed some other things. It will link properly now, but will be shown as `dragonfly.engines.backend_kaldi.audio.AudioStoreEntry`. I don't know if you can make Sphinx just show the last bit.

**Pull request merged**
