### PR TITLE
Implemented alpha support for accessibility API on Linux.

### PR DESCRIPTION
**Pull request by wolfmanstout**
I've successfully tested this on Linux using my Google API integration (which I still haven't cleaned up and committed upstream ... but it looks like things have moved well beyond that with the Kaldi integration). It's very similar to the Windows integration; just various name and interface changes here and there.

### CODE REVIEW

**Comment by Danesprite** [comment]
Thanks for this! I'm looking forward to trying it out. What applications have you tested with?

**Comment by wolfmanstout** [comment]
You're welcome!

Just Firefox, although that's a pretty good reference implementation I think. I've tested all the functionality; only stuff that doesn't work is when I need to fall back to Mouse.

**Comment by Danesprite** [comment]
Thanks. I can't seem to get this working with Firefox. I'm testing with the `move_cursor()` function. I have *pyatspi* installed, but it either says "Nothing is focused", "Focused element is not text." or fail without any warning message. I'm using some code adapted from your [_repeat.py module](https://github.com/wolfmanstout/dragonfly-commands/blob/master/_repeat.py).

I'm not familiar with how this all works underneath, but it looks like the controller threads can be daemonized so they exit with the main thread. This removes the need to explicitly call `controller.stop()`. Is there anything wrong with doing this?

**Comment by wolfmanstout** [comment]
Sorry, it had been so long since I set this up that I forgot an important detail: you need to add this to your ~/.profile:
export GNOME_ACCESSIBILITY=1

Assuming that's enough to get things working for you, I can update the documentation.

**Comment by Danesprite** [comment]
Thanks for this, but it doesn't seem to make a difference for me. It's definitely reading text from Firefox, but it just doesn't move the cursor or select words. It's not interference from any of my add-ons, as I get the same results with them all disabled. 

I'm not sure if the desktop environment and/or window manager makes a difference. I'm using Xfce with Xfwm4 on Debian 10. Firefox is up-to-date (v68.0.2). What environment are you using?

Apart from Firefox, I can say it is working very nicely with LibreOffice Writer. It doesn't detect words after new lines for some reason. Not sure if that's something you can fix. It also kind of works with the Xfce Mousepad text editor, although selection doesn't work.

I can add the two `thread.setDaemon(True)` lines I'm using if you want. It hasn't affected the results and makes it easier to use this :-)

**Comment by wolfmanstout** [comment]
There is a setting in Firefox to disable accessibility, and I think it might be enabled by default. You should be able to find it if you search within preferences. The setting is: "Prevent accessibility services from accessing your browser". Can you see if that's checked? Also, can you check to see if you can look at accessibility information within the inspector, which you can open with Ctrl+Shift+I? Based on the symptoms, it sounds like Firefox might be exposing some very rudimentary accessibility support, but blocking the deeper integration. Also, make sure to test the functionality in the address bar, because that's independent of any webpage.

I took a quick look at LibreOffice and I was definitely able to reproduce this issue. I'd have to spend some more time figuring out a clean way to fix this. In a nutshell, it exposes each paragraph as a separate focusable element. So from the perspective of the client, it's almost like each of these is a different form element on a webpage. Currently I scope selection to the currently focused element, because I think in general that's a better UX. I could check to see if immediate siblings are editable, though, and include those. I have also thought about exposing options which search the entire active application (although it might be really expensive). In principle that would be a great way to expose copy/paste of arbitrary read-only text within a webpage.

I guess the thread.setDaemon(True) lines make it easier for the process to close? With my Google API integration I organize execution in such a way that each of these background operations cleans up before the main thread finishes. I don't see any harm in having this, though, so feel free to make the change. Maybe it would also make sense to make that change in the Windows ia2.py file?

**Comment by Danesprite** [comment]
The "Prevent accessibility services from accessing your browser" setting wasn't checked and I can look at accessibility information within the inspector if I enable it. Unfortunately I get the same problems whether I test in the address bar or any web page. I'll try to reproduce this in a different environment and see if I can figure out what's going on.

Ah, that makes sense. Checking if the immediate siblings are editable sounds like a good fix. Searching the entire active application would be very useful, although as you say it could be computationally expensive.

I'm happy to merge this without a fix if you think it'll take a while, although maybe things like this should be mentioned in the documentation as known issues?

> I guess the thread.setDaemon(True) lines make it easier for the process to close?

Exactly. I'll add those changes shortly. I have verified that it also works with the Windows IA2 implementation, so I'll change that too.

**Comment by wolfmanstout** [comment]
Thank you. Updated the documentation. I think this is ready to go; I probably won't get to those improvements to the LibreOffice handling for a little while. These little things sometimes also affect Windows so it's not anything new here (it just comes down to how applications interface with the accessibility API).

It would certainly be great if we could get Firefox working on your machine; I'm worried I did something special but just forgot what that was. I'm using Ubuntu 18.04 with default configuration. I'm surprised that the window manager would make a difference, though, especially if you think that the connection to Firefox is working but it's just not accepting actions. What makes you think it is working at all? Do you see that it's getting text from the API?

**Comment by Danesprite** [comment]
Thanks for updating the documentation. No worries about the LibreOffice improvements. It's pretty impressive even with that limitation.

> What makes you think it is working at all? Do you see that it's getting text from the API?

Well, based on the logging output I thought it was sometimes getting text from Firefox, but now I'm certain it was actually reading text from my terminal window instead. It acts as if the Firefox window doesn't exist and instead uses the last focused window.

I've reproduced the problem on a fresh install of Xubuntu (VM), so I'm guessing it's related to Xfce or something it uses. I also don't have the problem on my laptop where I don't use Xfce.

I'm happy to merge this now. Thanks again for your work on this! :-)

**Comment by jcaw** [comment]
What happens when you enable GNOME accessibility?

```

**Comment by jcaw** [comment]
What happens when you enable GNOME accessibility in `gsettings`?

```bash
gsettings set org.gnome.desktop.interface toolkit-accessibility true 
```

There are also some other settings you might have to export:

```
export GTK_MODULES=gail:atk-bridge
export OOO_FORCE_DESKTOP=gnome
export GNOME_ACCESSIBILITY=1
export QT_ACCESSIBILITY=1
```

You can use this script to test the accessibility support of your environment:

https://www.freedesktop.org/wiki/Accessibility/AT-SPI2/

**Comment by Danesprite** [comment]
@jcaw Thank you for this! I've fixed the problem now. GNOME accessibility was not enabled and some of these variables were not exported. It's odd that these settings only affected Firefox for me. That `check-a11y` project is very useful! I'll include this in the accessibility documentation.

**Comment by Danesprite** [comment]
I've updated the documentation (3b8ede9).

**Comment by wolfmanstout** [comment]
Thanks everyone! That Linux accessibility info page is a goldmine, thank you for sharing!

**Comment by jcaw** [comment]
No worries! The documentation is very scattered.

**Pull request merged**
