### PR TITLE
Fix Kaldi ListRef bug not updating list

### PR DESCRIPTION
**Pull request by daanzu**
This should fix it.

### CODE REVIEW

**Comment by Danesprite** [comment]
Thanks for the fix. Maybe it's something wrong on my end, but now I'm getting the following error when trying to update a list:

```
[KALDI severity=-3] Assertion failed: (grammar_fst_filename == grammar_fsts_filename_map[old_grammar_fst])
[1]    29170 abort      python3 kaldi_module_loader.py
```

Maybe it's different on Linux or something?

**Comment by daanzu** [comment]
Hmm, maybe it's a separate problem. I will check it out on linux, and maybe get back to you for a minimal example.

**Comment by Danesprite** [comment]
Okay then :+1:

Here is the grammar I've been testing with:
```Python
from dragonfly import Function, Grammar, List, ListRef, MappingRule

def print_item(item):
    print(item)

# Set up a dragonfly list.
lst = List("lst")

def update_list():
    if lst:
        print("Removing item from list.")
        lst.pop()
    else:
        item = "list item"
        print("Added '%s' to the list." % item)
        lst.append(item)


class ExampleRule(MappingRule):
    mapping = {
        # Update and recognise from a dragonfly list.
        "update list": Function(update_list),
        "<item>": Function(print_item),
    }

    extras = [ListRef("item", lst)]


grammar = Grammar("List example")
grammar.add_rule(ExampleRule())
grammar.load()

```

**Comment by daanzu** [comment]
Pretty sure it's a linux-specific problem. Should be a quick fix.

**Comment by daanzu** [comment]
OK, that should really fix it now, hopefully. Plus, linux binaries should be faster now.

**Comment by Danesprite** [comment]
I can confirm that fixed it for me on Linux. Thanks! :+1:

**Pull request merged**
