### PR TITLE
Kaldi Updates

### PR DESCRIPTION
**Pull request by daanzu**
This should resolve all current issues, hopefully. There is one oddity that I haven't been able to consistently reproduce with cloud dictation, but I don't think that is used much currently anyway, and it is mostly working.

### CODE REVIEW

**Comment by daanzu** [comment]
Actually, hold on merging this.

**Comment by daanzu** [comment]
Ok, should be all good now, I think.

By the way, somewhere in the other dragonfly commits, a call to `logging.basicConfig()` was added to the main `__init__.py` (and maybe other changes), which breaks some of the Kaldi logging.

**Comment by Danesprite** [comment]
Great! Thanks for these. I can confirm the Kaldi tests are now passing for me on Linux.

I added the `logging.basicConfig()` call to avoid annoying `No handlers could be found for logger "X"` messages. Is there a way to work around the Kaldi logging issues introduced by that change?

I haven't tried the cloud dictation yet actually. Local dictation has been good enough for me during testing.

I know I said I would do another dragonfly2 release, I've just been busy. I will try to do that tomorrow.

**Comment by daanzu** [comment]
No problem about the release. It gives me time to fix my bugs!

Logging: I thought I understood the python logger, but I am actually a little confused about why and how it is having trouble. I will try to look into it.

**Comment by Danesprite** [comment]
Hmm, okay then. What exactly is going wrong with the logging?

**Comment by daanzu** [comment]
Now I am having trouble reproducing the problems. However, I also am not getting `No handlers could be found`, either, even after removing the call to `basicConfig`. Nevertheless, the standard advice for logging in libraries is [here](https://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library), which sounds like it should solve your problem and maybe cause fewer problems elsewhere?

**Comment by Danesprite** [comment]
There are only a few corner cases where messages are logged while importing dragonfly. I'll see if I can make those appear later. For example, logging unknown key messages during action execution.

Thanks for that HOWTO section, I had not read it before. It makes sense I guess. I don't think a `NullHandler` will be necessary, I'll just remove the `logging.basicConfig()` statement again and remember this next time someone mentions it.

**Comment by Danesprite** [comment]
Thanks! This looks good to me now.

@JasoonS Just letting you know that this reverts the change that fixed issue #115. I'll do what I suggested above. Dragonfly shouldn't be setting up logging handlers internally. It's easy enough for people to just call `logging.basicConfig()` or `dragonfly.log.setup_log()`.

I'll mention the `No handlers could be found for logger "X"` messages in the [logging documentation](https://dragonfly2.readthedocs.io/en/latest/logging.html) to make this clearer.

**Comment by Danesprite** [comment]
Actually, sorry @JasoonS, for some reason I mistook you for @MatthijsBurgh.

**Pull request merged**
