### PR TITLE
Some fixes for the natlink engine and its tests under py3

### PR DESCRIPTION
**Pull request by mrob95**
These are the simple ones, there are some more complex failures which I haven't really looked into yet.

### CODE REVIEW

**Comment by Danesprite** [comment]
Thanks! I'm looking forward to natlink working in Python 3 :)

Did you want to use this PR for also fixing the more complex failures?

**Comment by mrob95** [comment]
Yeah we can leave this open for now. I'm hoping to have a test build done in the next week or so

**Comment by Danesprite** [comment]
Okay then, sounds good.

**Comment by Danesprite** [comment]
@mrob95 I'd like to rebase and merge this now that Natlink is working with Python. Thanks again :+1:

**Pull request merged**
