### PR TITLE
Support running the test suites with different pytest options

### PR DESCRIPTION
**Pull request by daanzu**
It would be nice to have an CLI option to enable this, but I'm not sure how to add to it correctly/cleanly.

### CODE REVIEW

**Comment by Danesprite** [comment]
Thanks for this. I had wondered if there was a way to stop pytest from suppressing stdout. The clean way to do this would be to allow passing pytest arguments via setup.py. For example:

```Shell
# Single option
python setup.py test -o -s

# Multiple options
python setup.py test -o "-s -v"

```

I have this implemented already. I'm happy to just reuse this PR.

**Comment by daanzu** [comment]
Looks good!

**Comment by daanzu** [comment]
I added a note to remind people (myself) what the option is.

**Comment by Danesprite** [comment]
Great, thanks for that :)

**Pull request merged**
