### PR TITLE
Fix issues with German integers + update unit tests

### PR DESCRIPTION
**Pull request by Danesprite**
Re: #321.

- 1,000,000 is now spoken as "eine million", instead of "ein million".
- Plural million numbers are now spoken using "millionen" instead, e.g. 2,000,000 is "zwei millionen".

@tripfish

Do you mind checking to see if I have this right? I don't speak German, though I would like to. :-)

I have disallowed speaking "millionen" on its own on the assumption that it would be as ambiguous in German as it is to speak of an unknown number of millions in English. I have left "million" recognisable on its own.

### CODE REVIEW

**Comment by tripfish** [comment]
Thank you for the quick implementation! And of course I like to test it. :-)

I tested it again with Dragon and WSR. It works as expected now.
Speaking the word million on its own is okay too, but I don't think it comes up in practice. I would always speak "eine million" in german. In addition, Dragon sometimes recognizes a coherent word if you have a mapping like "print <n>". Dragon sometimes turns it into the word "Printmillion".

While testing, I noticed another thing that I unfortunately overlooked before.
Numbers like 101 one speaks einhunderteins (not einhundertein).

Here are some examples:
https://www.korrekturen.de/zahlwort/?zahl=101
https://www.korrekturen.de/zahlwort/?zahl=1000001
https://www.korrekturen.de/zahlwort/?zahl=1002001
https://www.korrekturen.de/zahlwort/?zahl=101000000

Sorry that I didn't notice that before. I hope that doesn't make things too complicated.
I am becoming more and more aware of how complicated the german language is.

**Comment by Danesprite** [comment]
Thanks for testing the changes and for clarifying how you would speak one million in German. :-)

It is interesting that Dragon will recognise "Printmillion" sometimes instead. You should be able to remove words like that from Dragon's vocabulary if they come up a lot.

I'm glad you have also picked up on this other issue. I will just fix this problem in this PR too. Language is a deceptively complicated thing, isn't it?

**Comment by tripfish** [comment]
The interesting thing is that these words don't even exist in this combination in the vocabulary. I can create any word with "million", for example "Eselmillion" (Esel is the german word for donkey) :-). Dragon simply combines any word with the word million. Even if they don't make sense.

Let me know if there is anything I can test.

**Comment by Danesprite** [comment]
Huh, that is rather odd. I guess Dragon is doing something different for German or this is a bug of some sort. Does training the word "million" help at all?

I have adjusted the German integer implementation to handle "ein" and "eins" differently. I think I have it right :-). Can you check?

**Comment by tripfish** [comment]
I think that's because you can combine words in German. Unlike in English, these are usually written together. For example: In German, car tires are combined from the words "Auto" and "Reifen" to the word "Autoreifen".

I did a more detailed test (Dragon and WSR). It works as expected now.

Many Thanks! I hope that was the last one. :-)

**Comment by Danesprite** [comment]
Right, German compound words. This was a problem I was having trouble with in PR #321. It is difficult to represent words or phrases like this in a grammar format where spaces are considered the word boundary. Writing a grammar to be spoken in a language which does not use spaces (e.g. Japanese) would pose similar problems, assuming the engine doesn't just ignore the spaces.

I'm curious as to whether WSR handles words like "Esel million" and "Autoreifen" properly. I would guess so, since it supports languages that Dragon doesn't.

Thanks for testing it with Dragon and WSR. Good to know it is working as expected now. Hopefully the grammar is all fixed. I'm happy to adjust it further if you find other issues though. :-)

**Pull request merged**
