### PR TITLE
Add Kaldi incompatible version error reporting

### PR DESCRIPTION
**Pull request by daanzu**
Does this seem reasonable, or too much added complication? (Also, this could wait until the next Kaldi update; I just wanted to check with @Danesprite.)

### CODE REVIEW

**Comment by Danesprite** [comment]
This works. I needed to add `import kaldi_active_grammar` into `engine.py` though.

Instead of checking the version yourself, you could use the `pkg_resources` module instead:
```Python
import pkg_resources
pkg_resources.require("kaldi_active_grammar~=0.7.4")

```

**Comment by daanzu** [comment]
Augh! I knew there must be an easy way to check the version, but after a few minutes of Googling, I decided I would spend less time just coding it myself. Thanks for the tip.

**Comment by Danesprite** [comment]
No worries :)

**Comment by daanzu** [comment]
Closing for the real PR.

**Comment by Danesprite** [comment]
Okay :+1:

**Pull request closed without merging**
