### PR TITLE
Add .pylintrc file & do code cleanup

### PR DESCRIPTION
**Pull request by Danesprite**
@LexiconCode I've added a very basic `.pylintrc` file (re: #77).

What else do you think should be in there? And do you think we should set up some way of checking pull requests using it?

### CODE REVIEW

**Comment by LexiconCode** [comment]
I think the more checks the better for any project. It's something I'd like to evolve with Caster as well. A few thoughts that are food for thought more than direct suggestions for implementation with my experience.

In its most basic form linting checks for syntax errors and at its most enforces code standards/style for example PEP8. Utilizing .pylintrc allows granular control of that style/standard. The question is what coding style would you enforce for the Dragonfly project and how is it enforced?

>What else do you think should be in there?

Part of that process is pick your coding style. For example PEP8: check PEP8 standard against the Dragonfly repository to see how many changes are needed to enforce the coding standard. Then evaluating what exceptions to PEP8 based on preference or practicality in  .pylintrc. Then once the code base is converted Which is in part a manual process (if that's desired you could enforce just future pull requests) enforce PEP8 on future pull requests. However I find whole process burdensome both on the maintainer and contributor.

> And do you think we should set up some way of checking pull requests using it?

Caster currently checks for syntax errors on pull requests because I find this process frustrating with coding style. It's difficult to enforce through code reviews and I'd rather take the debate/preference out of the picture but not place the burden on the contributor and maintainer. Ultimately I would like formatting to become more transparent after a while and we can focus on the content instead. 

Therefore my thought is to utilize [Black](https://black.readthedocs.io/en/stable/)[Github](https://black.readthedocs.io/en/stable/).
- The primary downside is it runs on only Python three but can convert 2.7 code
- It solves the issue mentioned above because it's auto-formatter that can be run locally or on every pull request.
- Black reformats entire files in place. It is not configurable. Which to me adds value of convenience and consistency across the code base.

Now contributors for Caster and Dragonfly have two very different communities. Casters community tends to attract individuals who are new to programming or that don't program by profession (I fall within that category). Whereas Dragonfly contributors tends to have mature experienced programmers. Therefore you may not have the same challenges enforcing a coding style for those that contribute.

**Comment by Danesprite** [comment]
Thanks for your in-depth thoughts on this! I think I'd like to loosely enforce PEP8 for pull requests. I guess we'll have to wait and see if that becomes burdensome. Admittedly the main reason I want to add a `.pylintrc` file is to stop my editor complaining about trivial things like naming style.

I will try configuring `pylint` to exclude a few things from PEP8 which are unsuitable. I'll also try out `Black` and get back to you. I don't think requiring Python 3 for code formatting/linting is much of a problem.

**Comment by Danesprite** [comment]
I've updated the `.pylintrc` file and cleaned up most code-style issues under `dragonfly.actions` and `dragonfly.windows`, excluding specific pylint checks for some files where it makes sense. I'd like to try to do this for all library source files, although that will probably take quite some time!

I also noticed and fixed some minor bugs in code that isn't run much. Hopefully this process reveals more sneaky bugs hiding in the codebase! :-)

**Comment by Danesprite** [comment]
I'll re-base and merge this now for version 0.20.0. I'll continue working on this process, I just don't want this many changes going stale. I haven't added `pylint` to the CI build yet.

Incidentally, I was thinking about when to run `pylint` in the development process. It takes quite a while to finish at the moment, even on sub-packages like `actions`. I'm wondering what your thoughts are on just manually running it as part of the release checklist for the moment. Then, if that reveals pressing issues that need to be resolved, they can be fixed before releasing the next version. What do you think?

For pull requests, it would be ideal if we could just run `pylint` on the changed files. It should be possible to do that with git, but I'm not sure if Travis CI is meant to be used that way.

**Comment by Danesprite** [comment]
Hmm. `pylint3` actually runs much quicker on its own outside of Emacs as I've been running it. Maybe adding it to the CI build or to GitHub actions wouldn't be all that bad once the code cleanup is complete.

**Pull request merged**
