### PR TITLE
Change German integer impl. to support compound words in range 20-99

### LINKED ISSUE #306: German numbers are required to be spoken as separate words
When using Dragonfly `IntegerRef` "extras" with the engine language set to German, numbers can't be spoken naturally as whole words. Instead, they must be spoken separately with short pauses. For example, one would have to say "ein und dreissig" instead of "einunddreissig" to match 31.

It should be possible to change Dragonfly's German number implementation ([number.py](https://github.com/dictation-toolbox/dragonfly/blob/master/dragonfly/language/de/number.py)) to accept either way of pronouncing German numbers.

Thanks @tripfish for reporting this on Gitter last month. I should have opened this issue back then, sorry.

### PR DESCRIPTION
**Pull request by Danesprite**
Closes #306.

This PR adjusts the German language integer implementation so that integers between 20 and 99 can be spoken either as one word or multiple words, e.g. 'ein und zwanzig' and 'einundzwanzig' for the integer 21. This also fixes the problem when speaking larger numbers that include these words.

The changes to the internal integer classes may be useful in other language implementations. Before merging, I will add extra functionality for only using what I have called "modified paths". This will allow, to use my above example, recognizing 'einundzwanzig', but not 'ein und zwanzig'. I don't think this should be enabled for German language integers, however.

@tripfish If you get a chance, could you give this branch a try and let me know if there are issues? It seems to be working with Dragon and with all the test integers I have used.

Sorry this took me so long BTW!

### CODE REVIEW

**Comment by tripfish** [comment]
@Danesprite Thank you for your work!

I did some tests with Dragon and WSR. The behavior mentioned here is solved. :-)
(The behavior did not previously occur with WSR. But it still works.)

When testing with large numbers, I noticed another problem. But this is something that existed before and has nothing to do with the fix. I just didn't notice it before. So I would consider this a separate bug.

It concerns numbers in the millions.
In German one speaks the number 1000000 "eine Million" (not "ein Million"). So that when speaking of "eine Million" the number is not recognized. Thus the pronunciation of the number 1131131 used in the test is also incorrect.

Also note that numbers like 2000000 are spoken "zwei Millionen" ("en" at the end).

You can get the words of the numbers on this website: https://www.korrekturen.de/zahlwort/?zahl=1131131

I don't think anyone will speak such large numbers in one word with dragonfly, so that this behavior is likely to rarely come into play. But I wanted to mention it for the sake of completeness. :-)

**Comment by Danesprite** [comment]
I'm glad to hear that it's working properly with Dragon and WSR. :-)

Thanks for bringing these other issues with German numbers to my attention. It is easy enough to change it so that "eine million" is used instead of "ein million". Using "millionen" for million numbers 2-9 isn't too difficult either. I will handle these in a separate PR. I agree that it is unlikely anyone will speak such large numbers.

This korrekturen.de website is very useful, much more so than Google Translate. Thanks! I notice that they give compound words for some larger numbers. It is possible to implement this in Dragonfly as well, however, it can be computationally expensive.

**Comment by tripfish** [comment]
@Danesprite
I'm glad to hear, that it is not too difficult to fix the million issue. And I think that's enough. I can't imagine anyone going to use even larger numbers. In my opinion, that would be more of a feature request. :-)

Thanks again!

**Comment by Danesprite** [comment]
Oh, I agree that numbers in the billions (or higher!) would be too much and would indeed be a feature request. Additional `IntegerContent` builders for billion numbers can be manually added by any user who needs them.

By "compound words for some larger numbers", I was referring to numbers like 131131. Dragonfly will accept "ein hundert einunddreissig tausend ein hundert einunddreissig" for this number, but not "einhunderteinunddreissigtausendeinhunderteinunddreissig". I tried adding modifier functions to allow for that and the space and time complexity made Dragonfly unusable. Compound words for numbers in the hundreds range — einhunderteinunddreissig, for instance — work fine, however there is a notable decrease in performance when building the `Integer` elements for the full range. Let me know if you think it would be useful to add those.

I will merge this now and open another PR for fixing the million number issues. Thank you for your help on all this! :-)

**Comment by tripfish** [comment]
Ah, got it. :-)
The current solution works with Dragon and WSR. Unfortunately I can't comment on kaldi or any other engine. If the other engines pass the words in the same way, I see no reason to add this option.

**Comment by Danesprite** [comment]
Ah, okay then. I will not add the option. Thanks again for your input. :-)

**Pull request merged**
