### PR TITLE
Add WSR/SAPI5 retain audio support; tweak documentation & gitignore

### PR DESCRIPTION
**Pull request by daanzu**
(gitignore: .idea was duplicated)

### CODE REVIEW

**Comment by Danesprite** [comment]
Thanks! Looks good. I'll do some testing soon.

This may be a silly question, but is SAPI5 documented somewhere? I found it difficult to work out what methods and attributes were available last time I made changes to *backend_sapi5/*. I also had trouble understanding exactly what error codes from SAPI5 actually mean.

**Comment by Danesprite** [comment]
I'm getting an error when testing this with `get_engine("sapi5inproc", retain_dir="recordings")`:
```
Traceback (most recent call last):
  File "w:\dragonfly-daanzu\dragonfly\engines\backend_sapi5\engine.py", line 488, in recognition_callback
    file_stream.Open(os.path.join(self.engine._retain_dir, filename), constants.SSFMCreateForWrite)
  File "C:\Python27\lib\site-packages\win32com\gen_py\C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4\ISpeechFileStream.py", line 40, in Open
    , FileMode, DoEvents)
com_error: (-2147352567, 'Exception occurred.', (0, None, u'Member not found.', None, 0, -2147287038), None)
```

I'm guessing this is a version difference between us. I get the error with the "sapi5inproc" and "sapi5shared" engines on both Windows 7 and 10 using recognizer version 8.0. Any ideas?

**Comment by Danesprite** [comment]
Okay never mind. Apparently that was because the folder didn't exist. Perfect example of confusing error messages from WSR.

I'll add some code to check whether the path exists and is a directory so that more sensible messages are given instead.

Otherwise this is pretty good! Nice job!

**Comment by daanzu** [comment]
Oops, I'd foolishly assumed WSR would generate a reasonable message if that happened, and neglected to test. Fix looks good!

**Comment by Danesprite** [comment]
No worries, it was a reasonable assumption to make. I'll merge this now. Thanks again! :+1:

**Pull request merged**
