### PR TITLE
Kaldi updates

### PR DESCRIPTION
**Pull request by daanzu**

### CODE REVIEW

**Comment by Danesprite** [comment]
These look like some nice improvements!

I'm having some trouble running the Dragonfly-Kaldi tests using this branch and your `kaldi_model_daanzu_20200905_1ep-mediumlm` model on Linux with Python 3.7. Do they run for you on Windows?

**Comment by daanzu** [comment]
@Danesprite Hmm, they run fine for me with that model on windows using python 3.6. (There's one failed test I need to look into and some warnings I need to fix though.) I haven't run the tests on linux recently. I am planning on working on setting up a cross platform full integration test suite for KaldiAG soon.

**Comment by Danesprite** [comment]
Okay then, sounds good. The Dragonfly-Kaldi tests didn't get past `test_contexts.py` for me on Linux. At that point, I had to kill the process because it quickly started using ~6GB of RAM. Since the "Loading Kaldi-Active-Grammar v1.8.0 in process X" message was printed frequently, I think the Kaldi decoder was being initialised over and over again.

There are some issues with the Dragonfly test suite calling `engine.connect()` and `engine.disconnect()` unnecessarily. I will fix these soon. There must be something else going on though, otherwise I would have encountered this issue previously.

**Comment by LexiconCode** [comment]
If memory serves correct when `engine.disconnect()` is called with Kaldi it doesn't disconnect gracefully something with sounddevice.

**Comment by Danesprite** [comment]
@LexiconCode Hmm. I do have a few `sounddevice` errors actually. I don't know why this would only affect me on Linux though.

**Comment by daanzu** [comment]
@Danesprite Is there a reason why Linux would run the tests in parallel and Windows wouldn't?

With the new `audio_input_device=False` engine parameter, you should be able to disable audio during tests, but I'm not sure the best place to add that.

**Comment by daanzu** [comment]
@Danesprite This runs tests fine (generally) for me on Linux with Python 3.5.

```
================================================================================ 2 failed, 51 passed, 1 warnings in 34.48 seconds ================================================================================
Command exited with non-zero status 1
28.48user 14.18system 0:40.35elapsed 105%CPU (0avgtext+0avgdata 11633792maxresident)k
0inputs+536outputs (0major+3507593minor)pagefaults 0swaps
```

**Comment by Danesprite** [comment]
The tests are not running in parallel. `connect()` is being called by the main thread each time.

I have tried running the tests again with audio disabled via that parameter. There was no difference unfortunately. What Kaldi model are you testing with?

**Comment by daanzu** [comment]
@Danesprite Hmm, there's probably some memory leaks from repeated connect/disconnects. That test was with kaldi_model_daanzu_20200905_1ep-mediumlm.

**Comment by Danesprite** [comment]
Okay then. Yup, it does sound like memory leaks. I'll see if I can fix it.

**Comment by daanzu** [comment]
@Danesprite It is almost assuredly in the native code side of KaldiAG, which is currently part way through a major overhaul for the next major version. It'll probably be easier for me to fold it in to that. I think the rest of this is ready to merge, and I don't think it's a regression.

**Comment by Danesprite** [comment]
Oh right, okay then :+1:. I'll merge now then and fix the excessive connect/disconnects in the test code when I can.

**Comment by daanzu** [comment]
Sounds good! I'm pretty sure there are leaks in my native code upon disconnect, but I don't think that's really used much outside of tests. Fewer connect/disconnects would help mask it too.

**Comment by LexiconCode** [comment]
Caster uses disconnect to disconnect the engine then calls from command line to relaunch the engine.

**Comment by daanzu** [comment]
@LexiconCode Ah, I didn't know that. Thanks for the info! I think I may have improved some of the audio disconnect handling recently. If it remains an annoyance, please poke me.

Do you call disconnect during do_recognition?

**Comment by LexiconCode** [comment]
> Do you call disconnect during do_recognition?

It shouldn't as its in a standard mapping rule. It's only used to completely restart the engine/caster and not related to reloading rules. Although as an experiment it would be interesting to try it in a mid CCR chain see what happens.

**Pull request merged**
