### PR TITLE
Linux port: implement Key and Text with xdotool

### PR DESCRIPTION
**Pull request by dwks**
Successfully perform Key and Text on native Linux. This implementation is based on aenea's xdotool backend (https://github.com/dictation-toolbox/aenea/blob/master/server/linux_x11/x11_xdotool.py).

I've left one print statement in for now, it will only affect Linux. It gives debugging output such as the following:
```
charlie
Keyboard.send_keyboard_events [('c', True, 0), ('c', False, 0.02)]
Keyboard.send_keyboard_events [('shift', False, 0.0), ('ctrl', False, 0.0), ('alt', False, 0.0)]
```

I've tested this fairly thoroughly on different keys using t4ngo's _multiedit (https://github.com/t4ngo/dragonfly-modules) and my aenea-grammar-simple.

### CODE REVIEW

**Comment by Danesprite** [comment]
Thank you very much for this!

I would like to try implementing it with [pynput](https://github.com/moses-palmer/pynput) instead, which would make it work on Mac OS too. That would also simplify the conditional imports a bit. I think I'll merge this if I don't have it done soon though.

Your implementation does give me some ideas for handling things like the `Keyboard` class depending on which OS is used.

The CI build is failing at the moment due to the print statement you mentioned, but that's easily fixed. This version of dragonfly has experimental support for Python 3.x. It seems to work with Pocket Sphinx. I'm happy to help with porting Python 2.7.x code as I've had quite a bit of experience with that now.

**Comment by dwks** [comment]
I intentionally left the aenea interface essentially unchanged, so that we can get the MacOS server implementation etc and they will all work. I think it's worthwhile having the pynput implementation, but there may be some value in this version too. For example there is a X11 Wayland implementation already in aenea.

I think the main two tricky parts here were realizing that I could use strings for the key codes in Typeable, and I could generate typing tables for standard keys like '/' automatically. Hopefully this will help whichever code ends up getting emerged.

I fixed the print but there are some global imports that are not Python 3 compatible.

**Comment by dwks** [comment]
Here is the MacOS aenea server.
https://github.com/dictation-toolbox/aenea/blob/master/server/osx/server_osx.py

**Comment by Danesprite** [comment]
I've fixed some incompatibility issues, including the import statement you mentioned. `Text` and `Key` work for me in both versions now. Python 3.6 is failing because of a global usage. I guess we can fix that later.

Yep, thanks for the work on Typeables. I think I've broken it on Windows with my changes. I'll see if I can fix it.

It makes sense to me to move additional implementations in from aenea, especially Wayland. I just wanted to avoid handling the mac implementation details myself really. I would like to support each platform eventually of course.

**Comment by Danesprite** [comment]
@dwks Just wanted to let you know I haven't forgotten about this. I have actually got most keys working on Linux/X11 using *pynput* instead. The implementation is also working on my mac. I'll put it up in a new branch after I've cleaned it up a bit.

**Comment by Danesprite** [comment]
I'm inclined to use the *pynput* implementation instead of this one. There are some extra keys working with that implementation that don't work with this one (e.g. caps lock, volume up, volume down) and key press delays are also supported.

Thanks for the work on it though! :-)

**Comment by dwks** [comment]
Sure, sounds good. As long as something works I don't really mind exactly how it is implemented. I look forward to seeing the full pynput implementation.

**Comment by Danesprite** [comment]
Yep, and it works pretty well at the moment from my testing.

It's possible to use either pynput or xdotool really; the design of the `dragonfly.actions.keyboard` sub-package supports that. Xdotool does handle a few things better, such as typing keys that aren't part of the keymap (e.g. the € key). So I might revisit this at some point if it's worth it.

**Pull request closed without merging**
