### PR TITLE
Kaldi backend (native on Linux & Windows)

### PR DESCRIPTION
**Pull request by daanzu**
A Kaldi backend, for testing & feedback. For more info, see [README](https://github.com/daanzu/dragonfly/tree/kaldi/dragonfly/engines/backend_kaldi) and [kaldi-active-grammar](https://github.com/daanzu/kaldi-active-grammar). Kaldi backend-specific issues, suggestions, and feature requests can be submitted there.

### CODE REVIEW

**Comment by Danesprite** [comment]
Great!

**Comment by daanzu** [comment]
New release with Linux support.

**Comment by lexxish** [comment]
This is awesome! How good is Kaldi compared to Dragon NaturallySpeaking? How does it compare to Google's Search by Voice (which is the best engine right now by far)?

**Comment by daanzu** [comment]
@lexxish Have you tested it out on your grammars? How did it do?

I don't personally use Dragon, but Kaldi is generally considered in the state-of-the-art range, at least when tuned and on open datasets. Of course, the datasets used for training are important, and Dragon & Google have huge private datasets to take advantage of. However, Kaldi is open, so we can adapt it to our specific usage, rather than whatever Nuance deigns to give us. (And Google doesn't support strict grammars at all.)

Also, I'm developing the ability to send just dictation recognitions from Kaldi off to Google Cloud Speech-to-Text to use their best-in-class dictation recognition (plus automatic capitalization/formatting/etc), along side Kaldi for low-latency true-grammar command recognition.

**Comment by Danesprite** [comment]
I've been trying this engine implementation with the examples in *dragonfly/examples* on Linux. I get a few errors about `ListRefs` and words not in the lexicon. These errors are expected of course, but the loader program terminates after I start speaking:

```
Speech started.
[KALDI severity=-3] Assertion failed: (ifsts_activity_.size() == activity.size())
[1]    22013 abort      python kaldi_module_loader.py
```

This doesn't happen if I test without lists.

I've also noticed a delay before speech can be processed. I'm guessing that the mic is recording while the model is prepared, which is pretty neat, but perhaps a message should be printed when the model is ready to accept speech?

**Comment by daanzu** [comment]
@Danesprite Good comments. Should be more user-friendly now. `ListRef` now will recognize initial elements of List at least.

**Comment by Danesprite** [comment]
Thanks. Recognizing initial elements is a good compromise.

**Comment by daanzu** [comment]
Another step towards partial implementation would be to recompile the ListRef's rule upon update and then reinitialize the decoder. This would mean a multi-second delay, and require a moderate amount of coding.

I have some ideas for a full implementation, too, but that'd take much more work. It'd also have an impact on decoding performance, but I'm unsure how significant.

**Comment by daanzu** [comment]
@Danesprite What things do you think should be done before merging this as a first version, so folks can try it out more easily?

**Comment by Danesprite** [comment]
It would be nice for lists to work as they do with the other engines. I don't have a problem with it being implemented later though if you want to merge this sooner.

> What things do you think should be done before merging this as a first version, so folks can try it out more easily?

Perhaps a test suite that can be run with `python setup.py test --test-suite=dragonfly.test.suites.kaldi_suite`? That wouldn't work without implementing `engine.unload_grammar()` though.

Another thing would be documenting the relevant engine methods so they appear on the [engines page](https://dragonfly2.readthedocs.io/en/latest/engines.html). Maybe the engine's README file should be linked to/included in the documentation?

**Comment by mrob95** [comment]
I'm writing this as I test it and as problems come up.

* First, I tried it with Python 3. It installed fine, but then dragonfly threw some errors as it seems there are still some instances of `Exception, e` lying around. Once these were fixed I am getting
```
$ python3 kaldi_module_loader.py
Traceback (most recent call last):
  File "kaldi_module_loader.py", line 86, in <module>
    main()
  File "kaldi_module_loader.py", line 68, in main
    engine.connect()
  File "c:\users\mike\documents\github\dragonfly2\dragonfly\engines\backend_kaldi\engine.py", line 71, in connect
    self._compiler = KaldiCompiler(self._model_dir, self._tmp_dir)
  File "c:\users\mike\documents\github\dragonfly2\dragonfly\engines\backend_kaldi\compiler.py", line 71, in __init__
    KAGCompiler.__init__(self, model_dir, tmp_dir)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python36\lib\site-packages\kaldi_active_grammar\compiler.py", line 74, in __init__
    self.exec_dir = os.path.join(utils.exec_dir, '')
AttributeError: module 'utils' has no attribute 'exec_dir'
```

* Switching to Python 2.7, pip installing k-a-g doesn't seem to be working, I just get 
```
$ python27 -m pip install kaldi-active-grammar
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting kaldi-active-grammar
  ERROR: Could not find a version that satisfies the requirement kaldi-active-grammar (from versions: none)
ERROR: No matching distribution found for kaldi-active-grammar
```
same thing happens from running `pip install .[kaldi]`

* Cloning the repo and installing manually (which also required [this](https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266) to install dependencies), running now produces this error message:
```
$ python27 kaldi_module_loader.py
Traceback (most recent call last):
  File "kaldi_module_loader.py", line 86, in <module>
    main()
  File "kaldi_module_loader.py", line 68, in main
    engine.connect()
  File "c:\users\mike\documents\github\dragonfly2\dragonfly\engines\backend_kaldi\engine.py", line 71, in connect
    self._compiler = KaldiCompiler(self._model_dir, self._tmp_dir)
  File "c:\users\mike\documents\github\dragonfly2\dragonfly\engines\backend_kaldi\compiler.py", line 71, in __init__
    KAGCompiler.__init__(self, model_dir, tmp_dir)
  File "c:\users\mike\documents\github\kaldi-active-grammar\kaldi_active_grammar\compiler.py", line 77, in __init__
    if not os.path.exists(self.exec_dir): raise KaldiError("cannot find exec_dir: %r" % self.exec_dir)
kaldi_active_grammar.KaldiError: cannot find exec_dir: 'c:\\users\\mike\\documents\\github\\kaldi-active-grammar\\kaldi_active_grammar\\exec\\windows\\'
```

Thoughts on where to go from here? Happy to give anything a try.

**Comment by daanzu** [comment]
@mrob95

Sorry, the python3 issue is [known](https://github.com/daanzu/kaldi-active-grammar/issues/1), but I forgot to update the README.

Do you know which particular package was needing a compiler on Windows? I'd hope they'd all have binary wheels.

Regarding installing KAG, its repo doesn't contain the required Kaldi interface binaries, which come in the PyPI package. Are you using a 64-bit python? If so, try updating your `pip` with `pip install --upgrade pip`?

**Comment by Danesprite** [comment]
I also initially had an issue with the wheel files not installing. I didn't mention it before because I knew it was something on my end (it worked in a virtual environment). Upgrading pip fixed it for me on Linux.

**Comment by mrob95** [comment]
@daanzu the package was `webrtcvad`.

I'm using 32-bit Python 2.7, is this likely to be the issue? If so then I will try on a VM later

**Comment by daanzu** [comment]
@mrob95 Yeah, sorry, 64-bit is a hard requirement for Kaldi. But you can easily install multiple pythons side-by-side. Just don't install the less favored one to your PATH.

**Comment by mrob95** [comment]
Okay my bad, should have read the instruction the more closely! Smooth sailing on 64-bit 2.7.

**Comment by daanzu** [comment]
Big additions. Testers will need to update `kaldi-active-grammar` to v0.3.0, and download the new model [here](https://github.com/daanzu/kaldi-active-grammar/releases/tag/v0.3.0).

**Comment by LexiconCode** [comment]
Will do! I will look into it this weekend.

**Comment by daanzu** [comment]
More additions. Testers will need to update `kaldi-active-grammar` to v0.4.0, and download the new model [here](https://github.com/daanzu/kaldi-active-grammar/releases/tag/v0.4.0).

I think the code might be ready to merge for beta testing. Three tests failing due to an issue with unloading rules, which can be avoided. I'm putting together some documentation.

**Comment by daanzu** [comment]
Hmm, Travis build is failing. Not sure why.

**Comment by Danesprite** [comment]
The Python 2.7 build is failing because of the following important statement in *test_engine_kaldi.py*:

```Python
from dragonfly.engines.backend_kaldi.engine import KaldiError

```

The `unittest.TestSuite` class doesn't seem to be good at reporting import errors. Perhaps this should be changed to:
```Python
try:
    from dragonfly.engines.backend_kaldi.engine import KaldiError
except ImportError:
    KaldiError = Exception
```

The Python 3.x builds are failing because of incompatible syntax in *dragonfly/engines/\_\_init\_\_.py*:

```
  File "/home/travis/build/dictation-toolbox/dragonfly/dragonfly/__init__.py", line 28, in <module>
    from .engines           import get_engine, EngineError, MimicFailure
  File "/home/travis/build/dictation-toolbox/dragonfly/dragonfly/engines/__init__.py", line 128
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

I can fix these issues if you want, just not sure if you have uncommitted work.

**Comment by daanzu** [comment]
Thanks for the tip on the import fix. There're probably various py3 issues (I've been waiting to test on py3); is just getting it compiling sufficient to merge it for now?

**Comment by Danesprite** [comment]
No worries. It's fine if there are issues with py3 inside *backend_kaldi*. Fixing that syntax error should make the build pass.

**Comment by daanzu** [comment]
Well, that was easier than I expected. It's likely worse in KAG, but that can wait for another day!

**Comment by Danesprite** [comment]
Yep! So this is ready for merging now?

**Comment by daanzu** [comment]
I *think* it's ready for merging. I'm still writing up some better documentation, but that should be easy to merge in later?

**Comment by Danesprite** [comment]
All right then. Sure, documentation can be added in later.

I've done some testing with your latest changes. I have said it before, but this is really impressive! It's very quick and I am getting very few misrecognitions!

Lists are working correctly for me, although the delay is noticeable as you've said. I can help with optimising the number of calls to `update_list()` via an optional context manager for multiple list updates. That would work for all engines and should be done separately. Perhaps the Kaldi engine should log a message about the delay before updating?

There are some minor things related to recognition observers that should be fixed before merging:

1. Recognition observers are notified after processing grammar rules. This should happen *before* processing so that events don't get out of sequence. Best example is if `mimic()` is used. The output for matching a command like `"mimic <text>"` will be printed out of order:

```
Speech started.
Recognized: some command
Recognized: mimic some command
```

This would also be noticeable for long-running commands; no output until afterwards.


2. The `KaldiEngine.mimic()` method should call `notify_begin()` as if speech had started. The `process_begin()` method should also be called for all grammars. Using the above example, the correct output would be:

```
Speech started.
Recognized: mimic some command
Speech started.                    <--- missing
Recognized: some command
```

3. I noticed that the engine does not call `notify_failure()` sometimes when I say something that doesn't match a grammar. It also doesn't do this for calls to `mimic()`. Any idea why?

**Comment by daanzu** [comment]
Thanks for testing it out, and finding these errors.

I'm mentioning the delay for ListRefs in the documentation. I didn't want to spam too many warnings. Coalescing `update_list`s would probably be nice, regardless of how much the engine is optimized.

1. This should be fixed now.
2. This should be fixed now. I think `process_begin()` was already being called.
3. Not sure about this. Have you noticed any patterns to it? Maybe turn log level on `engine` to DEBUG?

**Comment by Danesprite** [comment]
No worries. Mentioning the delay in the documentation is a better idea. Warning messages for it would be spammy now that you mention it. I'll make a separate issue on coalescing list updates.

Thanks for fixing these problems. `process_begin()` was being called once in my testing and only for the real utterance, not for the mimic call.

I can't seem to reproduce the 3rd issue. Maybe I was just being dismissed as noise? Not a big deal really. The first two issues were more important and it never happened when I was actually saying commands.

Happy to merge this now if you like. Should it be merged normally (without `--squash`)?

**Comment by daanzu** [comment]
Hmm, frequently the VAD will pick up noise and Kaldi will return an empty recognition of "". This should still generate a `notify_failure`, though. I guess just keep an eye out for it reoccurring.

I just added the documentation. Look reasonable? There's still some I should add eventually, but it's got the major stuff.

I'm fine with either merge type.

**Comment by Danesprite** [comment]
Okay then, I will keep an eye out for it :+1:

The documentation looks reasonable. I can see a few minor things that could be changed later.

One problem that should be fixed is that the docs won't build without the engine dependencies installed. You can test this by running the documentation build in a virtual environment (e.g. with [`virtualenv`](https://virtualenv.pypa.io/en/latest/)).

This could be fixed by mocking a few modules in *documentation/conf.py* (done for Windows-only things like `win32api`) or by catching the relevant import errors in *backend_kaldi/engine.py*. I've been doing the latter with the sphinx engine, but I think the first is much cleaner if you can get it working.

Just FYI, you've forgotten to import `PY2` and `locale` in *backend_kaldi/dictation.py* ;-)
```Python
import locale
from six import PY2
```

**Comment by Danesprite** [comment]
It would be nice if problems with the documentation build could be caught for pull requests. Read The Docs doesn't seem to report autodoc errors as errors for whatever reason. I'm open to suggestions on fixing this.

**Comment by daanzu** [comment]
Oops. Should be fixed now, plus some other fixes.

**Comment by Danesprite** [comment]
Great! The build looks good now. Thanks for mentioning the potential problems with installing `kaldi-active-grammar` :+1:

This looks ready to me. It seems to work well on Linux. Don't really want to go through installing 64-bit Python 2.7 on my Windows VM, so I'll assume it works well on there too.

Once this is merged I'll exclude the context tests from common test file names until they're fixed. Still not sure why the RPC mimic test is failing, but it's not a big deal. I should be able to release this in version 0.15.0 later today.

**Comment by daanzu** [comment]
I'm glad you're testing on Linux, because I'm developing on Windows and only occasionally testing Linux in a VM.

There's maybe one issue remaining: the webrtcvad package doesn't have a binary wheel for Windows, so you need to have the appropriate compiler installed. I'm asking the maintainer about posting one. If he doesn't, I could post one somewhere, and I assume there's a way to reference a URL in `setup.py`?

**Comment by Danesprite** [comment]
Yep, I figured you were developing on Windows. I'm glad we're not thinking of Mac OS at the moment.

That is a problem. I don't think you can link to other sources for wheel files, but I could be wrong. The relevant setuptools documentation section is this one: https://setuptools.readthedocs.io/en/latest/setuptools.html#dependencies-that-aren-t-in-pypi

Downloading a wheel file would be much easier than dealing with Microsoft's compiler packages.

**Comment by Danesprite** [comment]
So that doesn't really work if you're installing with pip. I think the easiest way is to install webrtcvad separately before running `pip install dragonfly2[kaldi]`:
```
pip install https://example.com/webrtcvad-cp27-cp27m-win_amd64.whl
```

**Comment by daanzu** [comment]
Fixed for now.

**Comment by Danesprite** [comment]
Looks good. I'll merge this now then.

**Pull request merged**
