### PR TITLE
Add __str__ method to essential action classes for visualization

### PR DESCRIPTION
**Pull request by dmakarov**
I would like to add these method for rules visualization purposes.  They provide mnemonic representation of actions that can be used to visualize the actions dragonfly rules invoke.

### CODE REVIEW

**Comment by alexboche** [comment]
I'm not going to pretend to have even read this pr, but I see something about visualization and reminded me that I should probably post the following [code](https://gist.github.com/alexboche/2d8ae71cc1b894d028b646f6ddacf920) and [output](https://gist.github.com/alexboche/73156ad19c54b842dcd46630d81070e1) for visualizing dragonfly grammars. not sure if this even still works since this is from a while ago. The code is written by caspark. Hope this is at least marginally relevant

**Comment by dmakarov** [comment]
The visualization that I mean is for GUI that I'm working on. It's a compact representation of an action associated with each phrase
Screen Shot 2020-03-06 at 18 16 37

**Comment by Danesprite** [comment]
This looks good to me. Thanks!

**Comment by daanzu** [comment]
Nice addition!

**Pull request merged**
